from __future__ import annotations

import csv
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]; DATA=ROOT/'apps/web/src/data'
COLS=['country','track','topic_tags','priority','source_type','source_title','source_url','resource_title','resource_url','resource_class','language','notes','access_model','verification_status','free_resource']
VERIFIED='Live source HTTP 200 · verified 2026-08-22'
FREE='Free public web resource'

# (country, slug, track, topic_tags, priority, source_type, source_title, source_url, resource_title, resource_url, resource_class, language, notes)
R=[
 ('Bangladesh','bangladesh','GA','mathematical olympiad;past papers;BdMO','A','Bangladesh Mathematical Olympiad Committee','BdMO past questions (official)','https://matholympiad.org.bd/bdmo-questions','BdMO regional and national round questions archive','https://matholympiad.org.bd/bdmo-questions','Exam archive','English/Bengali','First-party national olympiad committee page hosting downloadable past papers across all rounds and age categories via public cloud folder.'),
 ('Bangladesh','bangladesh','GA','olympiad training;problem archive;solutions','C','Gonitzoggo community platform','Gonitzoggo problem archive','https://gonitzoggo.com/archive/problems','Olympiad problem archive with solutions','https://gonitzoggo.com/archive/problems','Practice problems','English','Community-run practice platform affiliated with the Bangladeshi olympiad movement; hundreds of problems including past BdMO items with solutions.'),
 ('Bangladesh','bangladesh','EM','engineering mathematics;university exams;archive','A','BUET Central Library','BUET question papers repository (official)','http://lib.buet.ac.bd:8080/xmlui/handle/123456789/2144','BUET departmental question papers in DSpace','http://lib.buet.ac.bd:8080/xmlui/handle/123456789/2144','Exam archive','English','First-party university library archive of actual BUET departmental examination papers including math-heavy engineering units.'),
 ('Bangladesh','bangladesh','GA','admission test;MCQ;practice','C','Chorcha question bank','BUET admission question bank (English version)','https://chorcha.net/question-bank/buet-admission-question-bank-english-version','Past BUET admission-test questions (English version)','https://chorcha.net/question-bank/buet-admission-question-bank-english-version','Exam archive','English','Free English-version bank of past BUET admission-test mathematics and physics MCQs with answers; no login required.'),
 ('Viet Nam','vietnam','GA','VMO;olympiad problems;translations','C','Kalva problem archive','Vietnam Mathematical Olympiad problems 1962-2003','https://prase.cz/kalva/vietnam.html','VMO problem archive (English translations)','https://prase.cz/kalva/vietnam.html','Problem set','English','Established English-language archive of official Vietnam Mathematical Olympiad problems translated by medalists; decades of competition problems.'),
 ('Viet Nam','vietnam','GA','VMO geometry;curated problems','C','IMO Geometry blog','Vietnam MO geometry collection 1962-2022','https://imogeometry.blogspot.com/p/vietnam-mo.html','Curated VMO geometry problems with AoPS links','https://imogeometry.blogspot.com/p/vietnam-mo.html','Problem set','English','Curated set of ~95 VMO geometry problems in English, each linked to an Art of Problem Solving thread with community solutions.'),
 ('Viet Nam','vietnam','GA','THPT graduation exam;national exam;mathematics','A','Vietnam government portal','THPT 2023 graduation exam mathematics (official)','https://xaydungchinhsach.chinhphu.vn/thi-tot-nghiep-thpt-nam-2023-de-thi-mon-toan-va-goi-y-loi-giai-11923062818285233.htm','THPT 2023 mathematics paper with answer hints','https://xaydungchinhsach.chinhphu.vn/thi-tot-nghiep-thpt-nam-2023-de-thi-mon-toan-va-goi-y-loi-giai-11923062818285233.htm','Exam','Vietnamese','First-party state-portal reproduction of the official MOET national graduation mathematics paper covering all exam codes with suggested answers.'),
 ('Viet Nam','vietnam','GA','THPT graduation exam;past papers 2016-2024','C','ToanMath archive','Official THPT mathematics papers 2016-2024 compilation','https://toanmath.com/2024/07/tong-hop-51-de-thi-tot-nghiep-thpt-mon-toan-cua-bo-gddt-2016-2024.html','Compilation of official MOET THPT math papers','https://toanmath.com/2024/07/tong-hop-51-de-thi-tot-nghiep-thpt-mon-toan-cua-bo-gddt-2016-2024.html','Exam archive','Vietnamese','Free direct-PDF archive of every official Ministry of Education THPT graduation mathematics paper from 2016 to 2024, several with worked solutions.'),
 ('Myanmar','myanmar','GA','matriculation;past papers;national exam','A','Department of Myanmar Examination archive','Matriculation examination past papers (official)','http://resources.mmoe.myanmarexam.org','Matriculation exam paper archive (local and foreign streams)','http://resources.mmoe.myanmarexam.org','Exam archive','English','Official government S3 archive of matriculation mathematics papers for local and foreign streams from 2015 onward; papers printed in English.'),
 ('Myanmar','myanmar','GA','matriculation;mathematics paper','A','Department of Myanmar Examination archive','2020 matriculation mathematics paper (local stream)','http://resources.mmoe.myanmarexam.org/docs/old-questions/local/2020/IC2020-03-Mathematics.pdf','IC2020-03 Mathematics paper','http://resources.mmoe.myanmarexam.org/docs/old-questions/local/2020/IC2020-03-Mathematics.pdf','Exam','English','Direct official 2020 matriculation mathematics examination paper with substantive functions, calculus, geometry, and probability questions.'),
 ('Myanmar','myanmar','GA','matriculation;sample paper','A','Ministry of Education Myanmar','2019 matriculation sample mathematics paper III (official)','https://moe.gov.mm/sites/default/files/2019-ME-Sample-Question-math-iii.pdf','2019 sample mathematics paper III','https://moe.gov.mm/sites/default/files/2019-ME-Sample-Question-math-iii.pdf','Exam','English','Official ministry sample matriculation paper covering functions, polynomials, sequences, and circle-geometry proofs.'),
 ('Myanmar','myanmar','GA','MSM olympiad;solutions;team selection','C','Former MSM trainee solution notes','Myanmar Mathematical Olympiad Grade-11 selection solutions','https://radiuszero.github.io/public/solutions/G11Solutions.pdf','Grade-11 MSM selection exam solutions 2015-2019','https://radiuszero.github.io/public/solutions/G11Solutions.pdf','Solutions','English','Full English write-ups of all Grade-11 problems from the national olympiad team-selection examinations run by the Mathematical Society of Myanmar.'),
 ('Ethiopia','ethiopia','GA','EUEE;grade 12;past papers','B','Camara Education Ethiopia NEAEA mirror','EUEE Grade 12 mathematics past papers','https://camaraethiopia.org.et/CEE_National_Exam_New/Contents/Grade_12/G12_all.php?new_session_variable=Mathematics','Grade 12 EUEE mathematics papers','https://camaraethiopia.org.et/CEE_National_Exam_New/Contents/Grade_12/G12_all.php?new_session_variable=Mathematics','Exam archive','English','Mirror of national entrance-examination mathematics papers maintained by Camara Education Ethiopia; English-medium senior-secondary exam content.'),
 ('Ethiopia','ethiopia','GA','entrance exam;natural science stream','C','Kehulum practice portal','EUEE natural-science past exams','https://kehulum.com/entrance-exam/natural-science','Natural-science stream past mathematics exams','https://kehulum.com/entrance-exam/natural-science','Exam archive','English','Compiled ESSLCE/EUEE past mathematics examinations for the natural-science stream with free access.'),
 ('Ethiopia','ethiopia','GA','entrance practice;timed practice','C','Addis Entrance Hub','EUEE mathematics practice hub','https://addisentrancehub.com/model/math.html','Timed EUEE mathematics practice with explanations','https://addisentrancehub.com/model/math.html','Practice problems','English','Free timed computer-based practice on authentic national mathematics papers with instant scoring and step-by-step explanations.'),
 ('Türkiye','turkiye','GA','YKS;TYT/AYT mathematics;question books','A','MEB OGM Materyal','YKS past question books (official)','https://ogmmateryal.eba.gov.tr/yks-cikmis-soru-kitaplari','Ministry compilation of past YKS question books','https://ogmmateryal.eba.gov.tr/yks-cikmis-soru-kitaplari','Exam archive','Turkish','First-party Ministry of Education compilation of past national university-entrance question books as freely downloadable PDFs; sister page adds worked solutions.'),
 ('Türkiye','turkiye','GA','national olympiad;past problems;solutions','A','TÜBİTAK Bilim Olimpiyatları','National science olympiad past questions (official)','https://bilimolimpiyatlari.tubitak.gov.tr/tr/gecmis-sinav-sorulari','Mathematics olympiad past problems with solutions','https://bilimolimpiyatlari.tubitak.gov.tr/tr/gecmis-sinav-sorulari','Exam archive','Turkish','First-party TÜBİTAK archive of national mathematics olympiad first and second stage problems with answers and worked solutions reaching back to the late 1990s.'),
 ('Iran','iran','GA','geometry olympiad;problems;solutions','A','Iranian Geometry Olympiad secretariat','IGO official English archive','https://igo-official.com/?lang=en','Iranian Geometry Olympiad problems and solutions','https://igo-official.com/?lang=en','Exam archive','English','Official IGO secretariat site with full English problems-and-solutions booklets for all levels since 2014.'),
 ('Iran','iran','GA','geometry olympiad;booklet','A','Iranian Geometry Olympiad secretariat','IGO 2021 English booklet','https://igo-official.com/wp-content/uploads/2022/01/IGO_2021__English_-4.pdf','IGO 2021 booklet (English)','https://igo-official.com/wp-content/uploads/2022/01/IGO_2021__English_-4.pdf','Exam','English','Official 2021 Iranian Geometry Olympiad booklet with complete problems and solutions in English.'),
 ('Iran','iran','DM','combinatorics olympiad;problems;solutions','A','Iranian Combinatorics Olympiad','ICO official English archive','https://ico-official.com/en/archive','ICO problems-and-solutions archive','https://ico-official.com/en/archive','Exam archive','English','Official ICO archive with English booklets of combinatorics problems and full solutions; directly on-topic for the discrete-mathematics track.'),
 ('Iran','iran','DM','combinatorics olympiad;booklet','A','Iranian Combinatorics Olympiad','ICO 2020 English booklet','https://ico-official.com/assets/media/archive/ico-booklet-2020-en.pdf','ICO 2020 booklet (English)','https://ico-official.com/assets/media/archive/ico-booklet-2020-en.pdf','Exam','English','Official 2020 Iranian Combinatorics Olympiad booklet in English with problems and worked solutions.'),
 ('Iran','iran','GA','Iranian MO;translated problems','C','imomath problem collections','Problem collection for Iran','https://imomath.com/index.cgi?page=collectionIrn','Iranian Mathematical Olympiad problems 1984-2016 (English)','https://imomath.com/index.cgi?page=collectionIrn','Problem set','English','Standard English-facing archive of roughly 176 translated Iranian Mathematical Olympiad problems across all rounds since 1984.'),
 ('Iran','iran','EM','Iranian MO;solutions;selection tests','C','MOlympiad.NET','Iranian national olympiad 2010-2011 solutions','https://www.molympiad.net/2020/08/solutions-iranian-national-mathematical.html','Second round, third round, and TST solutions','https://www.molympiad.net/2020/08/solutions-iranian-national-mathematical.html','Solutions','English','English typeset solutions for the Iranian national olympiad second round, third round, and team-selection tests.'),
 ('Colombia','colombia','GA','OCM;olympiad;classification papers','A','Universidad Antonio Nariño OCM','Olimpiada Colombiana de Matemáticas pruebas (official)','http://oc.uan.edu.co/olimpiada-colombiana-de-matematicas/pruebas','OCM past classification and selection papers','http://oc.uan.edu.co/olimpiada-colombiana-de-matematicas/pruebas','Exam archive','Spanish','First-party host of the national olympiad: free PDFs of classification, selection, regional, and primary rounds across levels.'),
 ('Colombia','colombia','GA','OCM;problems and solutions;publications','A','Universidad Antonio Nariño OCM','OCM Problemas y Soluciones publications (official)','http://oc.uan.edu.co/component/k2/itemlist/category/17-publicaciones','Problems and solutions volumes','http://oc.uan.edu.co/component/k2/itemlist/category/17-publicaciones','Problem set','Spanish','Decades of olympiad problems with at least one full solution each, including final-round proof problems, published by the national olympiad.'),
 ('Brazil','brazil','GA','OBMEP;olympiad training;books','A','IMPA','OBMEP Math Circles collection (official)','https://impa.br/colecao/obmep-math-circles-collection/?lang=en','Math Circles book series in English','https://impa.br/colecao/obmep-math-circles-collection/?lang=en','Problem set','English','Official IMPA English page for the six-volume Math Circles series built on OBMEP problems with statements and solutions.'),
 ('Brazil','brazil','GA','OBMEP;problems;solutions','A','IMPA','Olympic Math Problems for Level 1 (official)','https://impa.br/books/olympic-math-problems-for-level-1/?lang=en','Olympic Math Problems Level 1 (English edition)','https://impa.br/books/olympic-math-problems-for-level-1/?lang=en','Problem set','English','English edition page of the introductory OBMEP-level problem collection with introductory through deepening problems and solutions.'),
 ('Brazil','brazil','GA','IMO 2017;competition archive','A','IMPA','IMO 2017 Rio archive (official)','https://impa.br/acervo/imo2017/competition.html','IMO 2017 problems and results','https://impa.br/acervo/imo2017/competition.html','Official gateway','English','Official IMPA English page for IMO 2017 hosted in Rio de Janeiro linking the competition problems and results archive.'),
 ('Mexico','mexico','GA','OMM;national olympiad papers','A','Mexican Mathematical Olympiad Society','OMM Concurso Nacional past papers (official)','https://www.ommenlinea.org/wp-content/uploads/concursos/nacionales/nac06.pdf','National contest problem booklets','https://www.ommenlinea.org/wp-content/uploads/concursos/nacionales/nac06.pdf','Exam','Spanish','Official Mexican Mathematical Olympiad national-contest paper series under the organiser site concurso uploads path; full problem statements.'),
 ('Mexico','mexico','GA','Tzaloa;olympiad magazine;problems','A','Mexican Mathematical Olympiad Society','Tzaloa OMM quarterly magazine (official)','https://www.ommenlinea.org/wp-content/uploads/2023/11/Tzaloa-4-2023.pdf','Tzaloa issue 4-2023','https://www.ommenlinea.org/wp-content/uploads/2023/11/Tzaloa-4-2023.pdf','Problem set','Spanish','Official OMM quarterly with practice problems and solutions, national and state exam papers, and international contest coverage.'),
 ('Mexico','mexico','EM','Cuadernos de Olimpiadas;training texts','A','UNAM Instituto de Matemáticas','Texedores collections (official)','https://texedores.matem.unam.mx/colecciones.html','Olympiad training-book collections with free downloads','https://texedores.matem.unam.mx/colecciones.html','Textbook','Spanish','UNAM mathematics institute official collections page including the Cuadernos de Olimpiadas and Papirhos training series with free electronic editions.'),
 ('Philippines','philippines','GA','PMO;olympiad;past papers with solutions','A','Philippine Mathematical Olympiad','PMO downloads archive','https://web.archive.org/web/20260228015917/https://pmo.ph/downloads/','PMO qualifying, area, and national papers with solutions','https://web.archive.org/web/20260228015917/https://pmo.ph/downloads/','Exam archive','English','Archive snapshot of the organiser downloads page holding over a decade of PMO stage papers with answers and full solutions; captured while pmo.ph was unavailable.'),
 ('Philippines','philippines','GA','UPCAT;admission test;reviewer','C','Review Masters UPCAT reviewer','Compiled UPCAT reviewer e-book','https://www.upcatreview.com/upcat-reviewer/','UPCAT mathematics reviewer download','https://www.upcatreview.com/upcat-reviewer/','Practice problems','English','Free downloadable reviewer compiling arithmetic-through-statistics questions drawn from past UPCAT examinee reports.'),
 ('Indonesia','indonesia','GA','KSM;madrasah competition;sample problems','C','Tirto education desk','KSM mathematics sample problems and keys','https://tirto.id/contoh-soal-ksm-matematika-mts-kabupaten-dan-kunci-jawaban-gMHr','KSM MTs sample problems with answer key','https://tirto.id/contoh-soal-ksm-matematika-mts-kabupaten-dan-kunci-jawaban-gMHr','Practice problems','Bahasa Indonesia','Worked sample problems for the Kompetisi Sains Madrasah mathematics competition aligned to the official syllabus strands with answer key.'),
 ('Indonesia','indonesia','EM','olympiad training;lecture notes','B','UGM Forum Matematika','UGM Forum Matematika materials (official)','https://forummatematika.mipa.ugm.ac.id/materi/','Olympiad-topic lecture notes and slides','https://forummatematika.mipa.ugm.ac.id/materi/','Problem set','Bahasa Indonesia','Faculty outreach materials from UGM mathematics department: HOTS strategies and olympiad-topic lecture notes across algebra, geometry, combinatorics, and number theory.'),
 ('Pakistan','pakistan','GA','NUST entry test;demo;mathematics','A','NUST undergraduate admissions','CBNET entry-test demo (official)','https://ugadmissions.nust.edu.pk/demo/index.htm','Official NET computer-based demo with mathematics sections','https://ugadmissions.nust.edu.pk/demo/index.htm','Practice problems','English','First-party interactive demo of the NUST entry test including the engineering/CS mathematics paper and BS-mathematics variant.'),
 ('Pakistan','pakistan','EM','GAT;sample test;mathematics','A','National University of Modern Languages','GAT-General mathematics sample test (official)','https://www.numl.edu.pk/campus/papers/1626670657sample%20test%20Mathematics.pdf','NUML GAT mathematics sample paper','https://www.numl.edu.pk/campus/papers/1626670657sample%20test%20Mathematics.pdf','Practice problems','English','University-published sample graduate-assessment mathematics section with quantitative MCQs on the NTS pattern.'),
 ('Pakistan','pakistan','GA','BISE Lahore;board exams;past papers','C','Pak Boards aggregator','BISE Lahore Class 9-12 mathematics past papers','https://pakboards.com/past-papers/bise-lahore/10/science','Year-wise board mathematics papers','https://pakboards.com/past-papers/bise-lahore/10/science','Exam archive','English/Urdu','Year-wise SSC/HSSC mathematics board examination papers (objective plus subjective) for the Lahore board, English and Urdu medium.'),
 ('Pakistan','pakistan','GA','NTS;GAT/NAT;quantitative samples','C','Paked NTS archive','NTS sample papers archive','https://paked.net/nts','GAT and NAT sample papers with quantitative sections','https://paked.net/nts','Practice problems','English','Long-standing archive of official National Testing Service sample papers with quantitative-reasoning sections and answer keys.'),
]


def main()->None:
    known=set()
    for p in DATA.glob('*.csv'):
        with p.open(newline='',encoding='utf-8') as h:
            for r in csv.DictReader(h):
                if r.get('resource_url'): known.add(r['resource_url'].strip().lower())
    counts={}; skipped=set()
    for row in R:
        url=row[9].strip().lower()
        if url in known: skipped.add(row[9]); continue
        out=DATA/f'{row[1]}_expansion_verified_resources.csv'
        rows=[]
        if out.exists():
            with out.open(newline='',encoding='utf-8') as h: rows=list(csv.DictReader(h))
            known.add(url)
        rec={'country':row[0],'track':row[2],'topic_tags':row[3],'priority':row[4],'source_type':row[5],'source_title':row[6],'source_url':row[7],'resource_title':row[8],'resource_url':row[9],'resource_class':row[10],'language':row[11],'notes':row[12],'access_model':FREE,'verification_status':VERIFIED,'free_resource':'Yes'}
        rows.append(rec)
        with out.open('w',newline='',encoding='utf-8') as h:
            w=csv.DictWriter(h,fieldnames=COLS); w.writeheader(); w.writerows(rows)
        counts[row[1]]=len(rows)
    print(f'Wrote tranches: {counts} ({sum(counts.values())} rows total)')
    if skipped: print('SKIPPED duplicates:',skipped)


if __name__=='__main__': main()
