from __future__ import annotations

import csv
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]; DATA=ROOT/'apps/web/src/data'
COLS=['country','track','topic_tags','priority','source_type','source_title','source_url','resource_title','resource_url','resource_class','language','notes','access_model','verification_status','free_resource']
VERIFIED='Live source HTTP 200 · verified 2026-08-22'
FREE='Free public web resource'

# (country, slug, track, topic_tags, priority, source_type, source_title, source_url, resource_title, resource_url, resource_class, language, notes)
R=[
 ('Finland','finland','GA','olympiad;training;problems','A','Finnish Mathematical Society','Matematiikkakilpailut olympiad training (official)','https://www.matematiikkakilpailut.fi/','Finnish olympiad problem sets and training handouts','https://www.matematiikkakilpailut.fi/materiaali.shtml','Problem set','Finnish','Official Finnish Mathematical Society IMO/EGMO training site with past competition problem sets and training handouts.'),
 ('Norway','norway','GA','Abelkonkurransen;competition;problems and solutions','A','Matematikksenteret NTNU','Abelkonkurransen archive (official)','https://abelkonkurransen.no/','Past Abel competition problems and solutions','https://abelkonkurransen.no/tidligere-konkurranser','Exam archive','Norwegian','National Norwegian mathematics competition archive with past problems and solutions since 1993.'),
 ('Denmark','denmark','GA','Georg Mohr;competition;problems','A','Georg Mohr-Konkurrencen','Georg Mohr competition (official)','https://www.georgmohr.dk/','Past Danish olympiad problems and solutions','https://www.georgmohr.dk/','Exam archive','Danish','Danish IMO-selection competition archive with past first and second round problems and solutions.'),
 ('Slovakia','slovakia','GA','Matematicka olympiada;problems','A','Slovak Mathematical Olympiad Committee','Matematicka olympiada archive (official)','https://skmo.sk/','Slovak olympiad tasks and solutions','https://skmo.sk/dokumenty','Exam archive','Slovak','Official Slovak Mathematical Olympiad task PDFs and solutions by year and category.'),
 ('Latvia','latvia','GA','olympiad;correspondence school;problems','A','University of Latvia correspondence school','NMS olympiad problem archive (official)','https://nms.lu.lv/','Latvian olympiad problem sets and materials','https://nms.lu.lv/','Problem set','Latvian','University of Latvia correspondence mathematics school with a large archive of olympiad and contest problem sets.'),
 ('Slovenia','slovenia','GA','national competitions;problems','A','DMFA Slovenije','DMFA national competitions (official)','https://www.dmfa.si/tekmovanja','National mathematics competition archives','https://www.dmfa.si/tekmovanja','Exam archive','Slovenian','Official DMFA national mathematics competition archives.'),
 ('Serbia','serbia','GA','olympiad;republic problems','A','Society of Mathematicians of Serbia','DMS competition archive (official)','https://www.dms.rs/','Republic-level competition problems and IMO prep','https://www.dms.rs/','Problem set','Serbian','Society of Mathematicians of Serbia archive of republic-level competition problems for primary and secondary school plus IMO preparation materials.'),
 ('Croatia','croatia','EM','Drzavna matura;state exams','A','NCVVO','Drzavna matura archive (official)','https://www.ncvvo.hr/','State matura mathematics papers','https://www.ncvvo.hr/','Exam archive','Croatian','Official Croatian state matura administered mathematics examination papers by school year.'),
 ('Bulgaria','bulgaria','GA','olympiad;resources;virtual classroom','A','Institute of Mathematics and Informatics BAS','IMI-BAS math education resources (official)','https://www.math.bas.bg/omi/','Bulgarian olympiad competitions and resources','https://www.math.bas.bg/omi/','Problem set','Bulgarian','Bulgarian Academy of Sciences mathematics-education section with olympiad competitions and virtual-classroom resources.'),
 ('Bulgaria','bulgaria','EM','IMC;university competition;problems','A','International Mathematics Competition','IMC university competition (official)','https://www.imc-math.org.uk/','IMC problems and solutions','https://www.imc-math.org.uk/?year=2024&item=problems','Problem set','English','International Mathematics Competition university-level problems and solutions in algebra, analysis, geometry, and combinatorics across years.'),
 ('Russia','russia','GA','olympiad;problem bank','A','problems.ru','Russian olympiad problem bank','https://problems.ru/','Large free Russian-language olympiad problem archive','https://problems.ru/','Problem set','Russian','Extensive free Russian-language mathematics problem archive organised by topic and level, including olympiad and entrance problems.'),
 ('Russia','russia','GA','olympiad;portal','A','Moscow Center for Continuous Math Education','MCCME olympiads portal','https://olympiads.mccme.ru/','Central Russian olympiad hub','https://olympiads.mccme.ru/','Official gateway','Russian','Moscow Center for Continuous Mathematics Education olympiad hub aggregating Russian national olympiad resources.'),
 ('Mongolia','mongolia','GA','APMO;regional olympiad;problems','B','Asian Pacific Mathematical Olympiad','APMO problems (official)','https://www.apmo-official.org/problems','APMO problems and solutions (Mongolia participant)','https://www.apmo-official.org/problems','Problem set','English','Official Asian Pacific Mathematical Olympiad problems and solutions; Mongolia is a core participant.'),
 ('Mongolia','mongolia','GA','school mathematics;guide','C','Zaavar math guide','Mongolian school mathematics guide','https://github.com/tuvshinbmgl-dna/zaavar-math-guide','Mongolian national-curriculum math guide','https://github.com/tuvshinbmgl-dna/zaavar-math-guide','Textbook','Mongolian','Open Mongolian-language school mathematics guide aligned to the national curriculum with adaptive assessment.'),
 ('Kyrgyzstan','kyrgyzstan','GA','e-olymp;online problems','C','E-olymp platform','E-olymp problem bank','https://e-olymp.com/','Central Asian online mathematics problem bank','https://e-olymp.com/','Problem set','Russian','Large free online problem bank used across Central Asia including Kyrgyzstan with topic and country filters.'),
 ('Kyrgyzstan','kyrgyzstan','DM','informatics olympiad;solutions','C','Regional olympiad solutions repo','Kyrgyzstan regional informatics olympiad','https://github.com/bofkutbilim/Kyrgyzstan-regional-olympiad-in-informatics','Informatics olympiad solutions 2018-2021','https://github.com/bofkutbilim/Kyrgyzstan-regional-olympiad-in-informatics','Problem set','Russian','Open repository of regional informatics-olympiad solutions with computational and discrete mathematics content.'),
 ('Bahrain','bahrain','GA','ministry;national exams','B','Bahrain Ministry of Education','Ministerial and national examinations (official)','https://moe.gov.bh/en/exams','National mathematics examination hub','https://moe.gov.bh/en/exams','Official gateway','Arabic/English','Official Bahrain Ministry of Education national-examination hub with mathematics among subjects.'),
 ('Qatar','qatar','EM','university;gateway','B','Qatar University','Qatar University mathematics portal','https://www.qu.edu.qa/','National university mathematics gateway','https://www.qu.edu.qa/','Official gateway','English','Qatar University national university portal hosting mathematics and science faculty course and examination material.'),
 ('Oman','oman','GA','ministry;national exams','B','Oman Ministry of Education','Oman national examinations (official)','https://home.moe.gov.om/','National mathematics examination hub','https://home.moe.gov.om/','Official gateway','Arabic/English','Official Oman Ministry of Education national-examination hub.'),
 ('Kuwait','kuwait','GA','ministry;national exams','B','Kuwait Ministry of Education','Kuwait national examinations (official)','https://www.moe.edu.kw/','National mathematics examination hub','https://www.moe.edu.kw/','Official gateway','Arabic/English','Official Kuwait Ministry of Education national-examination hub.'),
 ('Brunei','brunei','GA','ministry;national exams','B','Brunei Ministry of Education','Brunei national examinations (official)','https://www.moe.gov.bn/en','O/A-level mathematics examination hub','https://www.moe.gov.bn/en','Official gateway','English','Official Brunei Ministry of Education national-examination hub for O and A level mathematics.'),
 ('Maldives','maldives','GA','ministry;national exams','B','Maldives Ministry of Education','Maldives national examinations (official)','https://www.moe.gov.mv/','National mathematics examination hub','https://www.moe.gov.mv/','Official gateway','Dhivehi/English','Official Maldives Ministry of Education national-examination hub.'),
 ('Bhutan','bhutan','GA','ministry;curriculum','B','Bhutan Ministry of Education','Bhutan national curriculum (official)','https://www.education.gov.bt/curriculum','National curriculum and examinations','https://www.education.gov.bt/curriculum','Official gateway','English','Official Bhutan Ministry of Education national curriculum and examination gateway.'),
 ('Botswana','botswana','GA','BGCSE;exam board','A','Botswana Examinations Council','BGCSE qualifications (official)','https://www.bec.co.bw/','BGCSE mathematics assessment','https://www.bec.co.bw/index.php/qualifications-programmes/bgcse-products/bgcse-assesssment/bgcse-syllabi','Official gateway','English','Official Botswana Examinations Council BGCSE mathematics assessment and syllabus gateway.'),
 ('Eswatini','eswatini','GA','EGCSE;exam board','A','Examinations Council of Eswatini','EGCSE Mathematics (official)','https://www.examscouncil.org.sz/','EGCSE mathematics subject information','https://www.examscouncil.org.sz/programmes/subject.php?id=60&programme=EGCSE','Official gateway','English','Official Examinations Council of Eswatini EGCSE mathematics subject page.'),
 ('Lesotho','lesotho','GA','LGCSE;past papers','A','Examinations Council of Lesotho','Lesotho past papers (official)','https://www.examscouncil.org.ls/','LGCSE/JC past examination papers','https://www.examscouncil.org.ls/pastpapers','Exam archive','English','Official Examinations Council of Lesotho past-papers section for LGCSE and JC mathematics.'),
 ('Namibia','namibia','GA','NAMCOL;e-learning','B','NAMCOL','NAMCOL NotesMaster','https://namcol.edu.na/','NSSC mathematics notes and lessons','https://notesmaster.com','Textbook','English','National open-college e-learning portal with NSSC mathematics notes and video lessons.'),
 ('Namibia','namibia','GA','NIED;past question papers','A','National Institute for Educational Development','NIED past question papers (official)','https://www.nied.edu.na/','NSSC past-question-paper index','https://www.nied.edu.na/documents/questionpapers/index.html','Exam archive','English','Official NIED past-question-papers index for Namibia national secondary mathematics examinations.'),
 ('Mauritius','mauritius','GA','MIE;curriculum;textbooks','A','Mauritius Institute of Education','MIE curriculum books (official)','https://www.mie.ac.mu/','Primary and secondary mathematics textbooks','https://web.mie.ac.mu/curriculum_books/','Textbook','English','Official Mauritius Institute of Education primary and secondary mathematics syllabi and textbooks.'),
 ('Mauritania','mauritania','GA','baccalaureat;mathematics','C','Sigmaths','Baccalaureat mauritanien mathematics','https://www.sigmaths.net/bac2/mauritanie.php','Mauritanian bac mathematics papers with corrections','https://www.sigmaths.net/bac2/mauritanie.php','Exam archive','French/Arabic','Free mirror archive of Mauritanian baccalaureate mathematics papers across series with corrections.'),
 ('Congo','congo','GA','baccalaureat;mathematics','C','Sunudaara','Bac Congo mathematics','https://sunudaara.com/bac_congo','Congo baccalaureate mathematics papers with solutions','https://sunudaara.com/bac_congo','Exam archive','French','Free mirror archive of Republic of Congo baccalaureate mathematics papers with full solutions.'),
 ('Gabon','gabon','GA','baccalaureat;mathematics','C','Sunudaara','Bac Gabon mathematics','https://sunudaara.com/bac_gabon','Gabonese baccalaureate mathematics papers','https://sunudaara.com/bac_gabon','Exam archive','French','Free mirror archive of Gabonese baccalaureate mathematics papers with solutions.'),
 ('Comoros','comoros','GA','baccalaureat;mathematics','C','Sunudaara','Bac Union des Comores mathematics','https://sunudaara.com/bac_union_comores','Comorian baccalaureate mathematics papers','https://sunudaara.com/bac_union_comores','Exam archive','French','Free mirror archive of Comorian baccalaureate mathematics papers with solutions.'),
 ('Central African Republic','central_african_republic','EM','university;distance learning','B','Universite de Bangui','Universite de Bangui distance learning (official)','https://www.univ-bangui.cf/','FOAD distance-learning mathematics platform','https://lms.univ-bangui.cf/','Official gateway','French','Official University of Bangui distance-learning platform with mathematics course and assessment material.'),
 ('Libya','libya','EM','university;faculty of science','B','University of Tripoli','University of Tripoli Faculty of Science (official)','https://www.uot.edu.ly/sci/','Faculty of Science mathematics programmes','https://www.uot.edu.ly/sci/','Official gateway','Arabic','First-party University of Tripoli Faculty of Science portal with mathematics programmes and digital repository.'),
 ('Gambia','gambia','GA','WASSCE;chief examiner reports','A','WAEC Ghana (shared WASSCE)','WASSCE Mathematics chief examiner reports','https://waecgh.org/chief-examiners-report/','WASSCE mathematics report content','https://waecgh.org/chief-examiners-report/','Exam archive','English','WASSCE mathematics chief-examiner reports covering Gambia which sits the West African WASSCE.'),
 ('Liberia','liberia','GA','WASSCE;chief examiner reports','A','WAEC Ghana (shared WASSCE)','WASSCE Mathematics chief examiner reports','https://waecgh.org/chief-examiners-report/','WASSCE mathematics report content','https://waecgh.org/chief-examiners-report/','Exam archive','English','WASSCE mathematics chief-examiner reports covering Liberia which sits the West African WASSCE.'),
 ('Trinidad and Tobago','trinidad_and_tobago','EM','CSEC;subject report;examiner analysis','A','Caribbean Examinations Council','CSEC Mathematics subject report 2025 (official)','https://cxc.org/subject-reports/','CSEC mathematics subject report','https://cxc.org/wp-content/uploads/2018/11/RPT2025CSECMayJuneMathematicsSubjectReport.pdf','Exam','English','Official CXC CSEC mathematics subject report giving examiner analysis of real papers; CXC is the regional exam authority for Trinidad and Tobago.'),
 ('Guyana','guyana','EM','CAPE;subject report;examiner analysis','A','Caribbean Examinations Council','CAPE Integrated Mathematics subject report 2024 (official)','https://cxc.org/subject-reports/','CAPE integrated mathematics subject report','https://cxc.org/wp-content/uploads/2018/11/RPT2024CAPEJuneIntegratedMathematicsSubjectReport.pdf','Exam','English','Official CXC CAPE integrated mathematics subject report; CXC is the regional exam authority for Guyana.'),
 ('Samoa','samoa','GA','SSC;national exams;mathematics','A','Samoa Ministry of Education Sports and Culture','SSC examination papers (official)','https://www.mesc.gov.ws/education/ssc-papers/','Samoa School Certificate mathematics papers','https://www.mesc.gov.ws/education/ssc-papers/','Exam archive','English','Official Samoa School Certificate mathematics examination papers with full downloadable PDFs.'),
 ('Kiribati','kiribati','GA','national exams;past papers','A','Kiribati Ministry of Education','Kiribati past examinations (official)','https://www.moe.gov.ki/past-exams','SPFSC and school national papers','https://www.moe.gov.ki/past-exams','Exam archive','English/Kiribati','Official Kiribati Ministry of Education past-examination archive including SPFSC mathematics papers.'),
]


def main()->None:
    known=set()
    for p in DATA.glob('*.csv'):
        with p.open(newline='',encoding='utf-8') as h:
            for r in csv.DictReader(h):
                if r.get('resource_url'): known.add(r['resource_url'].strip().lower())
    counts={}; skipped=set()
    for row in R:
        url=row[9].strip().lower()
        if url in known: skipped.add(row[9]); continue
        out=DATA/f'{row[1]}_expansion_verified_resources.csv'
        rows=[]
        if out.exists():
            with out.open(newline='',encoding='utf-8') as h: rows=list(csv.DictReader(h))
            known.add(url)
        rec={'country':row[0],'track':row[2],'topic_tags':row[3],'priority':row[4],'source_type':row[5],'source_title':row[6],'source_url':row[7],'resource_title':row[8],'resource_url':row[9],'resource_class':row[10],'language':row[11],'notes':row[12],'access_model':FREE,'verification_status':VERIFIED,'free_resource':'Yes'}
        rows.append(rec)
        with out.open('w',newline='',encoding='utf-8') as h:
            w=csv.DictWriter(h,fieldnames=COLS); w.writeheader(); w.writerows(rows)
        counts[row[1]]=len(rows)
    print(f'Wrote tranches: {counts} ({sum(counts.values())} rows total)')
    if skipped: print('SKIPPED duplicates:',skipped)


if __name__=='__main__': main()
