from __future__ import annotations

import csv
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]; DATA=ROOT/'apps/web/src/data'
COLS=['country','track','topic_tags','priority','source_type','source_title','source_url','resource_title','resource_url','resource_class','language','notes','access_model','verification_status','free_resource']
VERIFIED='Live source HTTP 200 · verified 2026-08-22'
FREE='Free public web resource'

# (country, slug, track, topic_tags, priority, source_type, source_title, source_url, resource_title, resource_url, resource_class, language, notes)
R=[
 ('Ghana','ghana','GA','WASSCE;mathematics;examiner reports','A','WAEC Ghana','Chief Examiner reports archive (official)','https://waecgh.org/chief-examiners-report/','WASSCE/BECE mathematics chief examiner reports','https://waecgh.org/chief-examiners-report/','Exam archive','English','First-party WAEC Ghana archive of chief-examiner reports giving question-by-question commentary on real WASSCE and BECE mathematics questions.'),
 ('Zambia','zambia','GA','ECZ;specimen papers;grade 12','A','Examinations Council of Zambia','Guidelines and specimen papers (official)','https://www.exams-council.org.zm/guidlines/','Grade 9 and 12 specimen mathematics papers','https://www.exams-council.org.zm/guidlines/','Exam archive','English','Official ECZ page linking national specimen mathematics papers for the current curriculum.'),
 ('Zambia','zambia','GA','ECZ;past papers;grade 12','C','ZED Past Papers archive','Grade 12 ECZ mathematics past papers','https://zedpastpapers.com/downloads/grade12/index.html','ECZ grade 12 mathematics papers with marking schemes','https://zedpastpapers.com/downloads/grade12/index.html','Exam archive','English','Free direct-download archive of ECZ mathematics papers 2003-2024 with linked marking schemes per year.'),
 ('Malawi','malawi','GA','MANEB;MSCE;mathematics past papers','C','WTEC1 learning platform','MANEB mathematics past papers 2001-2019','https://ac.wtec1.com/maneb-mathematics-papers-2001-2019/','MSCE/JCE mathematics papers','https://ac.wtec1.com/maneb-mathematics-papers-2001-2019/','Exam archive','English','Third-party mirror of MANEB MSCE/JCE mathematics examination papers; the best free available collection for Malawi.'),
 ('Senegal','senegal','GA','Bac;epreuves;corriges','A','Office du Baccalaureat du Senegal','Epreuves et corriges du Bac (official)','https://officedubac.sn/category/epreuves-corriges/','Baccalaureat mathematics papers and answers','https://officedubac.sn/category/epreuves-corriges/','Exam archive','French','First-party Office du Bac archive of full Baccalaureat sessions with mathematics papers and corriges across series.'),
 ('Senegal','senegal','GA','Bac;annales;mathematics','C','Sigmaths','Bac Senegalais mathematics annales','https://www.sigmaths.net/bac2/Senegal.php','Senegal bac mathematics papers with corriges','https://www.sigmaths.net/bac2/Senegal.php','Exam archive','French','Free PDF archive of Senegalese baccalaureate mathematics papers with corriges back to 2006.'),
 ('Cameroon','cameroon','GA','Bac;probatoire;BEPC;corriges','B','CamerEcole portal','Examens mathematiques (national corrections)','https://www.camerecole.org/examens.html','BAC/Probatoire/BEPC mathematics papers and corriges','https://www.camerecole.org/examens.html','Exam archive','French','Education portal hosting national Cameroonian examination mathematics papers with harmonised national corriges 2009-2025.'),
 ('Cameroon','cameroon','GA','Bac;annales;mathematics','C','Sigmaths','Bac Camerounais mathematics annales','https://www.sigmaths.net/bac2/Cameroun.php','Cameroon bac mathematics papers with corriges','https://www.sigmaths.net/bac2/Cameroun.php','Exam archive','French','Free PDF archive of Cameroonian baccalaureate mathematics papers with corriges across series and BEPC/probatoire.'),
 ('Morocco','morocco','GA','2BAC;national exams;mathematics','C','Revisio.ma','Examens nationaux SM mathematiques','https://www.revisio.ma/ressources/examens-nationaux-sm-mathematiques','2BAC Sciences Maths A/B papers with corriges','https://www.revisio.ma/ressources/examens-nationaux-sm-mathematiques','Exam archive','French','Complete official 2BAC Sciences Maths national examinations with detailed corriges, direct PDF download.'),
 ('Morocco','morocco','GA','ONM;olympiad tests;problems','C','EMPIMO mediathique','Tests olympiques du Maroc','https://empimo.github.io/library/maroc.html','Moroccan olympiad tests and TST problems','https://empimo.github.io/library/maroc.html','Problem set','French/Arabic','Nonprofit olympiad-preparation archive of Moroccan Mathematical Olympiad tests and team-selection problems.'),
 ('Morocco','morocco','DM','MTYM;open problems;proofs','B','Math&Maroc MTYM','MTYM past-edition problems','https://mtym.mathmaroc.org/past-edition','Open research-style mathematics problems','https://mtym.mathmaroc.org/past-edition','Problem set','French','First-party NGO (former IMO team members) archive of open research-style proof problems across recent editions.'),
 ('Algeria','algeria','GA','Bac;annales;mathematics','C','Sigmaths','Baccalaureat Algerien mathematics annales','https://www.sigmaths.net/bac2/bacAlgerie.php','Algerian baccalaureate mathematics papers with corriges','https://www.sigmaths.net/bac2/bacAlgerie.php','Exam archive','French/Arabic','Free PDF archive of Algerian baccalaureate mathematics papers with corriges across filieres, principale and rattrapage sessions.'),
 ('Algeria','algeria','GA','Bac;anciens sujets;mathematics','C','Edukamer','Anciens sujets BAC Algerie mathematics','https://www.edukamer.info/anciens-sujet-de-mathematique-au-bac-algerie-pdf/','Bac mathematics papers 2015-2021','https://www.edukamer.info/anciens-sujet-de-mathematique-au-bac-algerie-pdf/','Exam archive','French/Arabic','Free PDF collection of Algerian baccalaureate mathematics papers by filiere with downloadable subjects.'),
 ('Tunisia','tunisia','GA','Bac;epreuves;corriges;mathematics','A','Centre National des Technologies en Education','Bacweb epreuves corrigees (official)','http://www.bacweb.tn/mma.htm','Bac mathematics epreuves and corriges 1994-2025','http://www.bacweb.tn/mma.htm','Exam archive','French/Arabic','First-party national education technology centre archive of Tunisian baccalaureate mathematics papers with official corriges across both sessions.'),
 ('Argentina','argentina','GA','OMA;olympiad;problems','A','Fundacion Olimpida Matematica Argentina','OMA enunciados archive (official)','https://www.oma.org.ar/enunciados/','OMA national-round problems by year and level','https://www.oma.org.ar/enunciados/','Problem set','Spanish','First-party foundation archive of OMA national mathematics olympiad problems by year and level.'),
 ('Argentina','argentina','GA','Olimpiada de Mayo;problems','A','Fundacion Olimpida Matematica Argentina','Olimpiada de Mayo enunciados 2018','https://oma.org.ar/enunciados/enunciados_Mayo%202018.pdf','Olimpiada de Mayo problem set 2018','https://oma.org.ar/enunciados/enunciados_Mayo%202018.pdf','Problem set','Spanish','Official multi-level Olimpiada de Mayo problem set with Iberoamerican scope used across Latin America.'),
 ('Argentina','argentina','GA','OMA;zonal;contest paper','A','Fundacion Olimpida Matematica Argentina','OMA zonal 2025 contest paper','https://www.oma.org.ar/contents/enunciados/pdf/oma/2025/oma_zonal_2025.pdf','OMA zonal 2025 (all levels)','https://www.oma.org.ar/contents/enunciados/pdf/oma/2025/oma_zonal_2025.pdf','Exam','Spanish','Official current-year OMA zonal contest paper covering all three age levels.'),
 ('Peru','peru','GA','ONEM;national school olympiad;sample items','A','MINEDU','ONEM cartilla and orientaciones (official)','https://cdn.www.gob.pe/uploads/document/file/7925348/6358579-ver-oficio-multiple-n-00112-2025-minedu-vmgi-drelm-ugel01-dir-agebre-difusion-de-orientaciones-y-cartilla-del-concurso-escolar-xxi-olimpiada-nacional-escolar-de-matematica-onem-2025-etapa-ie-14-04-2025.pdf?v=1744670454','ONEM 2025 stage-IE test spec and sample items','https://cdn.www.gob.pe/uploads/document/file/7925348/6358579-ver-oficio-multiple-n-00112-2025-minedu-vmgi-drelm-ugel01-dir-agebre-difusion-de-orientaciones-y-cartilla-del-concurso-escolar-xxi-olimpiada-nacional-escolar-de-matematica-onem-2025-etapa-ie-14-04-2025.pdf?v=1744670454','Practice problems','Spanish','First-party MINEDU ONEM stage-IE test specification with sample items mapped to national competencies.'),
 ('Peru','peru','GA','ONEM;problems;solutions','C','OnemPeru training blog','ONEM problem collections','https://onemperu.wordpress.com/category/problemas-semanales/','Weekly ONEM problems and solution books','https://onemperu.wordpress.com/category/problemas-semanales/','Problem set','Spanish','Authoritative ONEM training collection with weekly problems and full solutions across phases and levels.'),
 ('Peru','peru','GA','UNI;olympiad;university tier','A','Universidad Nacional de Ingenieria','UNI national mathematics olympiad (official)','https://admision.uni.edu.pe/uni-olimpiadas-matematicas/index.html','UNI olympiad school and university tracks','https://admision.uni.edu.pe/uni-olimpiadas-matematicas/index.html','Official gateway','Spanish','First-party UNI olympiad page covering school and first-year-university tracks with training materials.'),
 ('Chile','chile','GA','PAES;sample questions;mathematics','A','DEMRE','PAES mathematics sample questions (official)','https://demre.cl/la-prueba/ejemplos-preguntas/paes-p2023/intro-cmatematica.html','PAES mathematics modeled questions','https://demre.cl/la-prueba/ejemplos-preguntas/paes-p2023/intro-cmatematica.html','Practice problems','Spanish','First-party University of Chile admissions office page with modeled PAES mathematics questions and skill annotations.'),
 ('Chile','chile','GA','national olympiad;problems;paute','A','Sociedad de Matematica de Chile','Olimpiada Nacional de Matematica','https://www.olimpiadadematematica.cl/','National olympiad classification and final tests','https://www.olimpiadadematematica.cl/','Exam archive','Spanish','Official Chilean national mathematics olympiad archive of classification and final tests, many with solution keys.'),
 ('Venezuela','venezuela','GA','Olimpiada Juvenil;problems;solutions','A','ACFIMAN / Asociacion Matematica Venezolana','Olimpiada Juvenil de Matematica 2011','https://acfiman.org/wp-content/uploads/2023/01/Olimpiada-matematica-2011.pdf','Olimpiada Juvenil 2011 problems and solutions','https://acfiman.org/wp-content/uploads/2023/01/Olimpiada-matematica-2011.pdf','Problem set','Spanish','First-party national academy volume of the Venezuelan olympiad with preliminary, regional, and national problems and full solutions.'),
 ('Ecuador','ecuador','GA','OMEC;olympiad;training problems','A','OMEC','OMEC entrenamiento (official)','https://omec-mat.org/entrenamiento/','ONM problems and solutions 2016-2019','https://omec-mat.org/entrenamiento/','Problem set','Spanish','First-party national committee page with problems and solutions of all ONM levels plus weekly and selective-team exam archives.'),
 ('Bolivia','bolivia','GA','OPMAT;olympiad;problems and solutions','A','Universidad Mayor de San Andres','OPMAT Olimpiadas anteriores (official)','https://opmat.fcpn.edu.bo/oldopmat/','OPMAT editions with proofs and solutions','https://opmat.fcpn.edu.bo/oldopmat/','Problem set','Spanish','First-party university-hosted archive of Olimpiadas Pacenas editions each with problem and solution PDFs.'),
 ('Papua New Guinea','papua_new_guinea','GA','grade 10;national exam;paper','B','PNG Facts education portal','Grade 10 mathematics examination 2015','https://edu.pngfacts.com/grade-10-exams/grade-10-mathematics-examination-paper-2015-mc','Grade 10 national mathematics paper with answers','https://edu.pngfacts.com/grade-10-exams/grade-10-mathematics-examination-paper-2015-mc','Exam','English','Full national grade-10 mathematics paper with posted answers including MC and extended-response items.'),
 ('Papua New Guinea','papua_new_guinea','GA','national exams;compiled papers','B','World Possible RACHEL','Papua New Guinea exams module','https://rachel.worldpossible.org/viewmod/en-pngexams','Grades 8/10/12 national papers (offline module)','https://rachel.worldpossible.org/viewmod/en-pngexams','Exam archive','English','Compiled national examination papers produced in collaboration with the PNG Department of Education for offline distribution.'),
 ('Haiti','haiti','GA','Baccalaureat;state exam;mathematics','C','ExamHaiti','Baccalaureat haitien archive','https://www.examhaiti.com/examen-baccalaureat-haiti/','Haitian baccalaureate and fundamental exam subjects','https://www.examhaiti.com/examen-baccalaureat-haiti/','Exam archive','French','Free archive of Haitian state examination subjects including mathematics and fundamental-grade exams.'),
 ('Iraq','iraq','GA','ministerial exams;mathematics;compilation','C','iraqedu.net assistant','Ministerial-exam mathematics compilation','https://iraqedu.net/%D9%85%D9%84%D8%B2%D9%85%D8%A9-%D9%88%D8%B2%D8%A7%D8%B1%D9%8A%D8%A7%D8%AA-%D8%A7%D9%84%D8%B1%D9%8A%D8%A7%D8%B6%D9%8A%D8%A7%D8%AA-%D8%AE%D8%A7%D9%84%D8%AF-%D8%A7%D9%84%D8%AD%D9%8A%D8%A7%D9%84%D9%8A/','Wizarayat mathematics compilation for grade 6 scientific','https://iraqedu.net/%D9%85%D9%84%D8%B2%D9%85%D8%A9-%D9%88%D8%B2%D8%A7%D8%B1%D9%8A%D8%A7%D8%AA-%D8%A7%D9%84%D8%B1%D9%8A%D8%A7%D8%B6%D9%8A%D8%A7%D8%AA-%D8%AE%D8%A7%D9%84%D8%AF-%D8%A7%D9%84%D8%AD%D9%8A%D8%A7%D9%84%D9%8A/','Exam archive','Arabic','Compilation of Iraqi ministerial-examination mathematics problems for the sixth scientific grade covering algebra, calculus, and geometry.'),
 ('Iraq','iraq','GA','learning platform;mathematics exercises','C','Newton platform','Newton mathematics subject page','https://newton.iq/subjects/1','Mathematics lessons and weekly exercises with solutions','https://newton.iq/subjects/1','Practice problems','Arabic','Iraqi remote-learning platform mathematics page with lecture videos and weekly exercises with downloadable solutions.'),
 ('Jordan','jordan','GA','olympiad;question archive','C','Jo1jo education','Jordanian olympiad question sets','https://www.jo1jo.com/4852.html','Mathematics olympiad question PDFs (incl. English phase 2)','https://www.jo1jo.com/4852.html','Problem set','Arabic/English','Downloadable Jordanian mathematics olympiad question sets including an English phase-2 paper.'),
 ('Jordan','jordan','EM','Tawjihi;computerized exams;mathematics','C','JoQuiz','Tawjihi computerized mathematics exams','https://joquiz.com/category/%D8%A7%D9%85%D8%AA%D8%AD%D8%A7%D9%86%D8%A7%D8%AA-%D9%85%D8%AD%D9%88%D8%B3%D8%A8%D8%A9/%D8%A7%D9%85%D8%AA%D8%AD%D8%A7%D9%86%D8%A7%D8%AA-%D8%A7%D9%84%D8%B1%D9%8A%D8%A7%D8%B6%D9%8A%D8%A7%D8%AA-%D9%85%D8%AD%D9%88%D8%B3%D8%A8%D8%A9/','Tawjihi mathematics exam bank','https://joquiz.com/category/%D8%A7%D9%85%D8%AA%D8%AD%D8%A7%D9%86%D8%A7%D8%AA-%D9%85%D8%AD%D9%88%D8%B3%D8%A8%D8%A9/%D8%A7%D9%85%D8%AA%D8%AD%D8%A7%D9%86%D8%A7%D8%AA-%D8%A7%D9%84%D8%B1%D9%8A%D8%A7%D8%B6%D9%8A%D8%A7%D8%AA-%D9%85%D8%AD%D9%88%D8%B3%D8%A8%D8%A9/','Exam archive','Arabic','Free bank of Tawjihi computerized mathematics examinations for the scientific and literary branches.'),
 ('United Arab Emirates','united_arab_emirates','GA','MOE;textbook;mathematics curriculum','A','UAE Ministry of Education','MOE digital library mathematics textbook (official)','https://www.moe.gov.ae/En/pages/ereader.aspx','MOE mathematics textbook PDF (English curriculum)','https://tls.moe.gov.ae/FileService/Services/File.asmx/Download?id=05fb9343-89fa-432c-bf55-0a17e059e21d','Textbook','English','Official UAE Ministry of Education digital-library mathematics textbook with substantive worked mathematics content; free direct download.'),
 ('Kazakhstan','kazakhstan','DM','olympiad;problems;database','B','matol.kz','Republican mathematics olympiad problems','https://matol.kz/olympiads/1228','Olympiad problems by year and grade with solutions','https://matol.kz/olympiads/1228','Problem set','Russian/Kazakh','Database of Republican mathematics olympiad problems by year and grade, each with comments and solutions threads.'),
 ('Kazakhstan','kazakhstan','DM','olympiad;books library','B','matol.kz','matol.kz books library','https://matol.kz/books','Published olympiad problem books','https://matol.kz/books','Textbook','Russian/Kazakh','Collection of published olympiad problem books including regional, republican, and municipal compilations.'),
 ('Uzbekistan','uzbekistan','DM','Kenguru;olympiad;archive','B','Olympia platform','Olympia archive (official)','https://olympia.uz/uz/archive/index','Kenguru competition booklets and answer keys','https://olympia.uz/uz/archive/index','Exam archive','Uzbek/Russian/English','Archive of International Kenguru mathematics competition question booklets and answer keys for grades 1-11 in multiple languages.'),
 ('Azerbaijan','azerbaijan','DM','Republican olympiad;question booklets','B','tehsilim.info','Republican subject olympiad booklets','https://tehsilim.info/olimpiada-test-saullar/','RFO Riyaziyyat booklet index','https://tehsilim.info/olimpiada-test-saullar/','Exam archive','Azerbaijani/Russian','Index of Republican Subject Olympiad mathematics question booklets for grades 9-11 with direct PDF links.'),
 ('Azerbaijan','azerbaijan','DM','Republican olympiad;grade 9 booklet','B','Virtual Kitabxana','RFO Riyaziyyat grade 9 booklet','https://virtualkitabxana.files.wordpress.com/2019/01/RFO-I-riyaziyyat-az-9.pdf','Republican mathematics olympiad grade 9 booklet','https://virtualkitabxana.files.wordpress.com/2019/01/RFO-I-riyaziyyat-az-9.pdf','Exam','Azerbaijani','Direct PDF of the Republican Mathematics Olympiad question booklet for grade 9.'),
]


def main()->None:
    known=set()
    for p in DATA.glob('*.csv'):
        with p.open(newline='',encoding='utf-8') as h:
            for r in csv.DictReader(h):
                if r.get('resource_url'): known.add(r['resource_url'].strip().lower())
    counts={}; skipped=set()
    for row in R:
        url=row[9].strip().lower()
        if url in known: skipped.add(row[9]); continue
        out=DATA/f'{row[1]}_expansion_verified_resources.csv'
        rows=[]
        if out.exists():
            with out.open(newline='',encoding='utf-8') as h: rows=list(csv.DictReader(h))
            known.add(url)
        rec={'country':row[0],'track':row[2],'topic_tags':row[3],'priority':row[4],'source_type':row[5],'source_title':row[6],'source_url':row[7],'resource_title':row[8],'resource_url':row[9],'resource_class':row[10],'language':row[11],'notes':row[12],'access_model':FREE,'verification_status':VERIFIED,'free_resource':'Yes'}
        rows.append(rec)
        with out.open('w',newline='',encoding='utf-8') as h:
            w=csv.DictWriter(h,fieldnames=COLS); w.writeheader(); w.writerows(rows)
        counts[row[1]]=len(rows)
    print(f'Wrote tranches: {counts} ({sum(counts.values())} rows total)')
    if skipped: print('SKIPPED duplicates:',skipped)


if __name__=='__main__': main()
