from __future__ import annotations

import csv
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]; DATA=ROOT/'apps/web/src/data'
COLS=['country','track','topic_tags','priority','source_type','source_title','source_url','resource_title','resource_url','resource_class','language','notes','access_model','verification_status','free_resource']
VERIFIED='Live source HTTP 200 · verified 2026-08-22'
FREE='Free public web resource'

# (country, chunk_country_slug, track, topic_tags, priority, source_type, source_title, source_url, resource_title, resource_url, resource_class, language, notes)
R=[
 ('Australia','australia','GA','numeracy;NAPLAN;standardised testing','A','Australian Curriculum, Assessment and Reporting Authority archive','ACARA NAPLAN 2012-2016 test papers archive (official)','https://acara.edu.au/assessment/naplan/naplan-2012-2016-test-papers','NAPLAN 2012-2016 test papers archive','https://acara.edu.au/assessment/naplan/naplan-2012-2016-test-papers','Exam archive','English','Official ACARA archive of past NAPLAN test papers retained after live HTTP verification; substantive past numeracy test questions.'),
 ('Australia','australia','EM','past examinations;university mathematics','A','Western Sydney University library archive','Western Sydney University past exam papers repository (official)','https://library.westernsydney.edu.au/students/exam_papers','Past exam papers repository','https://library.westernsydney.edu.au/students/exam_papers','Official gateway','English','Official university repository of past final examinations including mathematics units; retained as first-party exam gateway.'),
 ('Australia','australia','EM','Mathematical Methods;external assessment;SACE','A','South Australian Certificate of Education assessment archive','SACE Mathematical Methods external assessment (official)','https://www.sace.sa.edu.au/web/mathematical-methods/external-assessment','SACE Mathematical Methods external assessment page','https://www.sace.sa.edu.au/web/mathematical-methods/external-assessment','Official gateway','English','Official SACE external-assessment page with past Mathematical Methods examination materials.'),
 ('Australia','australia','EM','Mathematical Methods;VCE;past examinations','A','Victorian Curriculum and Assessment Authority archive','VCAA Mathematical Methods examination archive (official)','https://www.vcaa.vic.edu.au/assessment/vce/examination-specifications-past-examinations-and-examination-reports/mathematical-methods','VCE Mathematical Methods past examinations and reports','https://www.vcaa.vic.edu.au/assessment/vce/examination-specifications-past-examinations-and-examination-reports/mathematical-methods','Official gateway','English','Official VCAA archive page for VCE Mathematical Methods past examinations, assessment reports, and exam specifications.'),
 ('Australia','australia','GA','school mathematics competition;problem solving','A','UNSW School of Mathematics and Statistics','UNSW School Mathematics Competition (official)','https://www.unsw.edu.au/science/our-schools/maths/engage-with-us/high-school-students-and-teachers/unsw-school-mathematics-competition','UNSW School Mathematics Competition page','https://www.unsw.edu.au/science/our-schools/maths/engage-with-us/high-school-students-and-teachers/unsw-school-mathematics-competition','Official gateway','English','First-party organiser page for the UNSW School Mathematics Competition with entry information and past-problem access points.'),
 ('Australia','australia','GA','video lessons;secondary mathematics','C','Independent Australian mathematics video resource','Maths Videos Australia project lessons','https://mathsvideosaustralia.com/project152/','Maths Videos Australia lesson collection','https://mathsvideosaustralia.com/project152/','Video lessons','English','Free Australian secondary-mathematics video lesson collection; third-party but openly accessible teaching videos.'),
 ('Australia','australia','EM','statistics;university coursework;solutions','A','University of Queensland course archive','UQ STAT2201 course worked-example archive (official)','https://courses.smp.uq.edu.au/STAT2201/2017a/Extras/Example2_Solution.pdf','STAT2201 worked example 2 with solutions','https://courses.smp.uq.edu.au/STAT2201/2017a/Extras/Example2_Solution.pdf','Solutions','English','Official UQ statistics course PDF containing fully worked example questions with complete solutions.'),
 ('Australia','australia','EM','engineering mathematics;sample exams;solutions','A','Monash University course archive','Monash ENG1091 sample exam with solutions (official)','https://users.monash.edu/~leo/moodle/eng1091/exams/sample-solutions.pdf','ENG1091 sample exam with solutions','https://users.monash.edu/~leo/moodle/eng1091/exams/sample-solutions.pdf','Exam','English','Official Monash engineering-mathematics unit sample exam with full solutions hosted on the faculty teaching server.'),
 ('Australia','australia','EM','financial mathematics;sample exams;solutions','A','Monash University course archive','Monash MTH3051 sample exam with solutions (official)','https://users.monash.edu/~leo/moodle/mth3051/exams/sample-solutions.pdf','MTH3051 sample exam with solutions','https://users.monash.edu/~leo/moodle/mth3051/exams/sample-solutions.pdf','Exam','English','Official Monash mathematics unit sample exam with full solutions hosted on the faculty teaching server.'),
 ('India','india','GA','entrance preparation;practice questions','C','Anand School entrance-preparation archive','ASB entrance-support question bank PDF','https://www.asb.ac.in/storage/entrance_support/entrance_support_1669744918.pdf','Entrance-support practice question bank','https://www.asb.ac.in/storage/entrance_support/entrance_support_1669744918.pdf','Practice problems','English','Institution-hosted entrance-support PDF with substantive mathematics practice questions; retained after live verification.'),
 ('India','india','GA','arithmetic;simple interest;worked questions','C','Leverage Edu exam-preparation article','Simple interest questions and answers with worked solutions','https://leverageedu.com/discover/indian-exams/exam-prep-simple-interest-questions-and-answers/','Simple interest solved question set','https://leverageedu.com/discover/indian-exams/exam-prep-simple-interest-questions-and-answers/','Practice problems','English','Openly accessible article containing substantive simple-interest practice questions with worked answers for Indian exam preparation.'),
 ('India','india','GA','design aptitude;CEED;admissions','A','IIT Bombay CEED examination portal','CEED 2025 official information and papers portal','https://www.ceed.iitb.ac.in/2025/','CEED 2025 official portal','https://www.ceed.iitb.ac.in/2025/','Official gateway','English','First-party IIT Bombay portal for the Common Entrance Examination for Design including syllabus, past-paper pointers, and admission material.'),
 ('India','india','GA','civil services;previous year papers;quantitative aptitude','A','Union Public Service Commission archive','UPSC previous question papers (official)','https://upsc.gov.in/examinations/previous-question-papers','UPSC previous question papers archive','https://upsc.gov.in/examinations/previous-question-papers','Exam archive','English','Official UPSC archive of previous-year question papers including quantitative-aptitude and general-studies components.'),
 ('India','india','DM','discrete mathematics;computer science;textbook','B','IIT Guwahati faculty course mirror','Mathematics for Computer Science open-textbook mirror','https://www.iitg.ac.in/pbhaduri/cs514-12/Mathematics%20for%20Computer%20Science%20(2011%20May%20book).pdf','Mathematics for Computer Science (May 2011) PDF','https://www.iitg.ac.in/pbhaduri/cs514-12/Mathematics%20for%20Computer%20Science%20(2011%20May%20book).pdf','Textbook','English','Faculty-hosted copy of the Lehman-Leighton-Meyer discrete-mathematics text used for CS514; substantive proofs and exercises, freely accessible.'),
 ('India','india','GA','management aptitude;ATMA;question paper with answers','A','AIMS ATMA official question-paper archive','AIMS ATMA 25 April 2021 question paper','https://www.atmaaims.com/pdf/QP/AIMS_ATMA_25_APR_2021.pdf','ATMA 2021-04-25 question paper PDF','https://www.atmaaims.com/pdf/QP/AIMS_ATMA_25_APR_2021.pdf','Exam','English','Official ATMA testing-body question-paper PDF with quantitative and analytical sections; retained after live HTTP verification.'),
 ('Israel','israel','EM','placement test;university mathematics','A','Hebrew University of Jerusalem overseas admissions','HUJI mathematics placement test 2024 questions (official)','https://overseas.huji.ac.il/wp-content/uploads/2024/01/math-placement-test-2024-questions.pdf','2024 mathematics placement test - questions','https://overseas.huji.ac.il/wp-content/uploads/2024/01/math-placement-test-2024-questions.pdf','Exam','English','Official Hebrew University placement-examination question paper; substantive university-entry mathematics questions.'),
 ('Israel','israel','EM','placement test;university mathematics','A','Hebrew University of Jerusalem overseas admissions','HUJI mathematics placement test 2024 answers (official)','https://overseas.huji.ac.il/wp-content/uploads/2024/01/math-placement-test-2024-answers.pdf','2024 mathematics placement test - answers','https://overseas.huji.ac.il/wp-content/uploads/2024/01/math-placement-test-2024-answers.pdf','Solutions','English','Official answer key for the 2024 Hebrew University mathematics placement test.'),
 ('Israel','israel','EM','linear algebra;final exam;solutions','A','HUJI Moodle course archive','Linear algebra winter 2022 final exam with solutions','https://moodle4.cs.huji.ac.il/hu23/pluginfile.php/103504/mod_resource/content/1/linear%20algebra%20exam%20winter%2020220702%20-%20solution.pdf','Linear algebra winter 20220702 exam with solutions','https://moodle4.cs.huji.ac.il/hu23/pluginfile.php/103504/mod_resource/content/1/linear%20algebra%20exam%20winter%2020220702%20-%20solution.pdf','Exam','English','Official Hebrew University Moodle-hosted linear algebra final examination with full worked solutions.'),
 ('Israel','israel','EM','linear algebra;final exam;solutions','A','HUJI Moodle course archive','Linear algebra Moed A 2023 final exam with solutions','https://moodle4.cs.huji.ac.il/hu23/pluginfile.php/103500/mod_resource/content/1/winter%20exam%20linear%20algebra%20moed%20a%2020232002-%20solution.pdf','Linear algebra Moed A 20232002 exam with solutions','https://moodle4.cs.huji.ac.il/hu23/pluginfile.php/103500/mod_resource/content/1/winter%20exam%20linear%20algebra%20moed%20a%2020232002-%20solution.pdf','Exam','English','Official Hebrew University Moodle-hosted linear algebra final examination with full worked solutions.'),
 ('Israel','israel','EM','linear algebra;final exam;solutions','A','HUJI Moodle course archive','Linear algebra Moed A 2024 final exam with solutions','https://moodle4.cs.huji.ac.il/hu23/pluginfile.php/496443/mod_resource/content/1/winter%20exam%20linear%20algebra%20moed%20a%2020240704%20solution.pdf','Linear algebra Moed A 20240704 exam with solutions','https://moodle4.cs.huji.ac.il/hu23/pluginfile.php/496443/mod_resource/content/1/winter%20exam%20linear%20algebra%20moed%20a%2020240704%20solution.pdf','Exam','English','Official Hebrew University Moodle-hosted linear algebra final examination with full worked solutions.'),
 ('Israel','israel','EM','linear algebra;final exam;solutions','A','HUJI Moodle course archive','Linear algebra summer 2021 final exam with solutions','https://moodle4.cs.huji.ac.il/hu23/pluginfile.php/103506/mod_resource/content/1/summer%20exam%20linear%20algebra%2020211310-%20solution.pdf','Linear algebra summer 20211310 exam with solutions','https://moodle4.cs.huji.ac.il/hu23/pluginfile.php/103506/mod_resource/content/1/summer%20exam%20linear%20algebra%2020211310-%20solution.pdf','Exam','English','Official Hebrew University Moodle-hosted linear algebra final examination with full worked solutions.'),
 ('Israel','israel','EM','probability;midterm exam','A','Technion course archive','Technion probability midterm 1 (official)','https://mzhi.net.technion.ac.il/files/2021/05/midterm-1.pdf','Probability midterm 1 exam','https://mzhi.net.technion.ac.il/files/2021/05/midterm-1.pdf','Exam','English','Official Technion course-site midterm examination PDF with substantive probability questions.'),
 ('Israel','israel','EM','probability;midterm exam;solutions','A','Technion course archive','Technion probability midterm 1 solutions (official)','https://mzhi.net.technion.ac.il/files/2021/05/midterm-1-solutions.pdf','Probability midterm 1 solutions','https://mzhi.net.technion.ac.il/files/2021/05/midterm-1-solutions.pdf','Solutions','English','Official Technion course-site midterm solutions PDF.'),
 ('Israel','israel','EM','calculus;problem sets;lecture notes','B','Technion-affiliated faculty course archive','Calculus course notes and problem material','https://yehudayoff.net.technion.ac.il/files/2015/10/calculus15.pdf','Calculus 2015 course PDF','https://yehudayoff.net.technion.ac.il/files/2015/10/calculus15.pdf','Problem set','English','Faculty-hosted calculus course material with substantive exercises; retained after live HTTP verification.'),
 ('United States','united_states','EM','probability;textbook;course mirror','B','Emory University teaching mirror','Larsen 5th-edition probability text (course-hosted mirror)','https://math.emory.edu/~lchen41/teaching/2020_Spring/Larsen-5E.pdf','Larsen 5E probability textbook PDF','https://math.emory.edu/~lchen41/teaching/2020_Spring/Larsen-5E.pdf','Textbook','English','University course-hosted full textbook PDF with end-of-section exercises; openly accessible teaching mirror.'),
 ('United States','united_states','EM','actuarial mathematics;theory of interest','B','University of Cincinnati course archive','PV2020 actuarial/interest-theory course PDF','https://homepages.uc.edu/~brycwz/classes/4008/PV2020.pdf','PV2020 course packet','https://homepages.uc.edu/~brycwz/classes/4008/PV2020.pdf','Course packet','English','Faculty-hosted actuarial-mathematics course packet with worked financial-mathematics material; freely accessible.'),
 ('United States','united_states','DM','discrete mathematics;computer science;textbook','B','Portland State University open-book mirror','Mathematics for Computer Science (LLM) open-book copy','https://web.cecs.pdx.edu/~antoy/Courses/CS250/open_books/LLM.pdf','Lehman-Leighton-Meyer Mathematics for Computer Science PDF','https://web.cecs.pdx.edu/~antoy/Courses/CS250/open_books/LLM.pdf','Textbook','English','University open-book shelf copy of the MIT discrete-mathematics text; substantive definitions, theorems, and exercises.'),
 ('United States','united_states','DM','discrete mathematics;computer science;textbook','B','UC Davis course mirror','MIT Mathematics for Computer Science course-book copy','https://www.cs.ucdavis.edu/~rogaway/classes/20/fall21/mit-book.pdf','MIT 6.042 Mathematics for Computer Science PDF','https://www.cs.ucdavis.edu/~rogaway/classes/20/fall21/mit-book.pdf','Textbook','English','Faculty-hosted copy of the MIT Mathematics for Computer Science text used in a UC Davis course; exercises and proofs throughout.'),
 ('United States','united_states','DM','discrete mathematics;computer science;textbook','B','University of Houston course mirror','UH discrete-structures course open-book copy','https://www2.cs.uh.edu/~arjun/courses/ds/','Discrete Mathematics for Computer Science textbook PDF','https://www2.cs.uh.edu/~arjun/courses/ds/DiscMaths4CompSc.pdf','Textbook','English','Course-hosted copy of a discrete-mathematics-for-computer-science text with substantive exercises; openly accessible after live HTTP verification.'),
 ('United States','united_states','EM','calculus;practice problems','A','Loyola University Chicago sample-final archive','MATH 118 practice problems (official)','https://www.luc.edu/media/lucedu/math/docs/samplefinalexams/MATH118_practice_problems.pdf','MATH 118 practice problems PDF','https://www.luc.edu/media/lucedu/math/docs/samplefinalexams/MATH118_practice_problems.pdf','Practice problems','English','Official Loyola University Chicago mathematics-department sample-final practice problems with substantive precalculus/calculus questions.'),
 ('United States','united_states','DM','discrete mathematics;video lectures;computer science','C','Academic personal lecture archive','Shai Simonson discrete-mathematics lecture series page','https://sites.google.com/site/shaisimonson/professional-page?authuser=0','Discrete mathematics video lecture series','https://sites.google.com/site/shaisimonson/professional-page?authuser=0','Video lectures','English','Professor-authored page hosting a complete free discrete-mathematics video lecture series (Stonehill/ADU); retained as lecturer-owned content.'),
 ('United States','united_states','GA','Putnam;competition problems;archive','A','Kedlaya Putnam archive','William Lowell Putnam competition archive','https://kskedlaya.org/putnam-archive/','Putnam problems and solutions archive','https://kskedlaya.org/putnam-archive/','Exam archive','English','Organizer-curated archive of Putnam competition problems and official solutions maintained by Kiran Kedlaya.'),
 ('Canada','canada','EM','final exams;cegep mathematics;archive','A','Dawson College mathematics department','Dawson College previous final exams (official)','https://www.dawsoncollege.qc.ca/mathematics/previous-final-exams/','Previous final examination archive','https://www.dawsoncollege.qc.ca/mathematics/previous-final-exams/','Exam archive','English','Official Dawson College mathematics-department archive of previous final examinations across calculus, linear algebra, and related courses.'),
 ('Canada','canada','EM','mathematics education;problems;collection','B','Simon Fraser University faculty publication','Zbornik 2 mathematics collection (Jungic)','https://www.sfu.ca/~vjungic/Zbornik2/Zbornik2.pdf','Zbornik 2 PDF','https://www.sfu.ca/~vjungic/Zbornik2/Zbornik2.pdf','Problem set','English','SFU faculty-authored mathematics collection with substantial worked problems; openly accessible.'),
 ('Canada','canada','DM','MACM 101;discrete mathematics;course materials','A','Simon Fraser University CourseCentral','MACM 101 course materials page (official)','https://www2.cs.sfu.ca/CourseCentral/101.MACM/evgenys/','MACM 101 discrete mathematics materials','https://www2.cs.sfu.ca/CourseCentral/101.MACM/evgenys/','Official gateway','English','Official SFU CourseCentral page hosting MACM 101 discrete-mathematics course assessments and materials.'),
 ('Canada','canada','EM','calculus;midterm;solutions','A','University of Alberta course archive','MATH 117/118 midterm 1 with solutions (official)','https://www.math.ualberta.ca/~xinweiyu/117-118.14-15/20140926Midterm1_sol.pdf','2014 MATH 117/118 midterm with solutions','https://www.math.ualberta.ca/~xinweiyu/117-118.14-15/20140926Midterm1_sol.pdf','Exam','English','University of Alberta faculty-hosted calculus midterm with complete solutions.'),
 ('Canada','canada','GA','diploma exam;Mathematics 30-1;released items','A','Alberta Education diploma-exam archive','Mathematics 30-1 released items 2019 (official)','https://www.alberta.ca/system/files/custom_downloaded_images/ed-diploma-exam-math-30-1-released-Items-2019.pdf','2019 Mathematics 30-1 released diploma items','https://www.alberta.ca/system/files/custom_downloaded_images/ed-diploma-exam-math-30-1-released-Items-2019.pdf','Exam','English','Official Alberta Education released diploma-examination items with substantive senior-secondary mathematics questions.'),
 ('Canada','canada','GA','diploma exam;Mathematics 30-1;practice test','A','Alberta Education practice-material archive','Mathematics 30-1 practice test (official)','https://www.alberta.ca/system/files/custom_downloaded_images/edc-mathematics-30-1-practice-test.pdf','Mathematics 30-1 practice test','https://www.alberta.ca/system/files/custom_downloaded_images/edc-mathematics-30-1-practice-test.pdf','Practice problems','English','Official Alberta Education practice test with questions aligned to the Mathematics 30-1 diploma examination.'),
 ('Canada','canada','EM','MATH 300;course page;university mathematics','B','University of Alberta course page','MATH 300 course materials page','https://www.math.ualberta.ca/~thillen/math300/math300.html','MATH 300 course page','https://www.math.ualberta.ca/~thillen/math300/math300.html','Official gateway','English','Faculty-maintained MATH 300 course page linking assignments and assessment material; retained after live HTTP verification.'),
 ('South Africa','south_africa','GA','NSC;matric;past papers','A','Department of Basic Education archive','2024 NSC November past papers (official)','https://www.education.gov.za/2024NSCNovemberpastpapers.aspx','2024 NSC November past papers','https://www.education.gov.za/2024NSCNovemberpastpapers.aspx','Exam archive','English','Official national archive of 2024 National Senior Certificate November examination papers including mathematics and technical mathematics.'),
 ('South Africa','south_africa','GA','outreach;problem magazine;olympiad training','A','University of Cape Town mathematics department','Mathematical Digest outreach magazine (official)','https://science.uct.ac.za/department-mathematics/outreach-mathematical-digest/overview','Mathematical Digest overview','https://science.uct.ac.za/department-mathematics/outreach-mathematical-digest/overview','Official gateway','English','First-party UCT page describing and indexing the Mathematical Digest problem magazine for South African schools.'),
 ('South Africa','south_africa','GA','mathematics olympiad;competition','A','University of Cape Town mathematics department','UCT Mathematics Olympiad (official)','https://science.uct.ac.za/department-mathematics/challenge-uct-mathematics-olympiad','UCT Mathematics Olympiad page','https://science.uct.ac.za/department-mathematics/challenge-uct-mathematics-olympiad','Official gateway','English','Official UCT page for its mathematics olympiad including participation details and problem access points.'),
 ('South Africa','south_africa','GA','mathematics olympiad;invitational challenge','A','UCT Mathematics Competition organisers','UCT invitational challenge page (official)','https://www.uctmathscompetition.org.za/invitationalchallenge','Invitational challenge','https://www.uctmathscompetition.org.za/invitationalchallenge','Official gateway','English','Organiser-owned page for the UCT Mathematics Competition invitational challenge round.'),
 ('New Zealand','new_zealand','GA','economics;competition;questions and answers','A','University of Auckland Business School','NZ Economics Competition previous questions and answers (official)','https://www.auckland.ac.nz/en/business/about-business-school/economics/nz-economics-competition/previous-questions-answers.html','Previous questions and answers','https://www.auckland.ac.nz/en/business/about-business-school/economics/nz-economics-competition/previous-questions-answers.html','Exam archive','English','Official University of Auckland archive of previous New Zealand Economics Competition questions and answers.'),
 ('New Zealand','new_zealand','DM','COMPSCI 101;past exams;archive','A','University of Auckland Computer Science','COMPSCI 101 past exams (official)','https://www.cs.auckland.ac.nz/courses/compsci101s1c/exams/','COMPSCI 101 past exam archive','https://www.cs.auckland.ac.nz/courses/compsci101s1c/exams/','Exam archive','English','Official departmental archive of COMPSCI 101 past examinations with mathematical-reasoning content.'),
 ('New Zealand','new_zealand','DM','COMPSCI 210;past exams;archive','A','University of Auckland Computer Science','COMPSCI 210 past exams (official)','https://www.cs.auckland.ac.nz/courses/compsci210s2c/exams/','COMPSCI 210 past exam archive','https://www.cs.auckland.ac.nz/courses/compsci210s2c/exams/','Exam archive','English','Official departmental archive of COMPSCI 210 past examinations covering computer-architecture mathematics.'),
 ('China','china','EM','placement test;MA1200;calculus','A','City University of Hong Kong','CityU MA1200 placement test sample (official)','https://www.cityu.edu.hk/ma/sites/g/files/asqsls6306/files/2022-08/ptest_ma1200_sample.pdf','MA1200 sample placement test','https://www.cityu.edu.hk/ma/sites/g/files/asqsls6306/files/2022-08/ptest_ma1200_sample.pdf','Exam','English','Official CityU mathematics-department sample placement test with calculus and linear-algebra diagnostic questions.'),
 ('Lebanon','lebanon','GA','mathematics olympiad;training','A','American University of Beirut','AUB mathematics olympiad program (official)','https://www.aub.edu.lb/cams/Pages/Olympiad.aspx','AUB Olympiad training page','https://www.aub.edu.lb/cams/Pages/Olympiad.aspx','Official gateway','English','Official AUB Center for Advanced Mathematical Sciences page for its national olympiad training program and problem sessions.'),
 ('Nigeria','nigeria','GA','SS1;practice questions;secondary mathematics','C','Adesoye College teaching resource','SS1 mathematics practice questions','https://adesoyecollege.org/wp-content/uploads/2020/07/SS1-MATHS-PRACTICE-QUESTIONS.pdf','SS1 mathematics practice questions PDF','https://adesoyecollege.org/wp-content/uploads/2020/07/SS1-MATHS-PRACTICE-QUESTIONS.pdf','Practice problems','English','School-published practice-question set for Senior Secondary 1 mathematics; substantive exercises, freely accessible.'),
 ('Jamaica','jamaica','GA','junior mathematical olympiad;archive','A','University of the West Indies Mona','Junior Mathematical Olympiad archives (official)','https://www.mona.uwi.edu/mathematics/junior-mathematical-olympiad-priimary-school-archives','Junior Mathematical Olympiad primary-school archives','https://www.mona.uwi.edu/mathematics/junior-mathematical-olympiad-priimary-school-archives','Exam archive','English','Official UWI Mona archive of Jamaica Junior Mathematical Olympiad past papers for primary schools.'),
 ('Italy','italy','GA','IMAT;medical admissions;past papers','C','IMAT Buddy past-paper collection','IMAT past papers collection','https://www.imatbuddy.com/imat-past-papers/','IMAT past papers','https://www.imatbuddy.com/imat-past-papers/','Exam archive','English','Free collection of past IMAT (Italian medical-admissions) papers with logical-reasoning and quantitative sections.'),
 ('Italy','italy','GA','IMAT;medical admissions;past papers','C','MedSchool.it IMAT archive','Previous IMAT test papers','https://medschool.it/blog/previous-imat-test-papers/','Previous IMAT test papers','https://medschool.it/blog/previous-imat-test-papers/','Exam archive','English','Openly accessible index of official previous IMAT test papers used for Italian medical-school admissions.'),
 ('United Kingdom','united_kingdom','DM','British Informatics Olympiad;programming problems','A','British Informatics Olympiad','BIO computing problems archive (official)','https://olympiad.org.uk/problems.html','BIO past computing problems','https://olympiad.org.uk/problems.html','Exam archive','English','Official British Informatics Olympiad archive of past computational problem-solving tasks.'),
 ('Saudi Arabia','saudi_arabia','EM','MATH 254;final exam;solutions','A','King Saud University faculty archive','MATH 254 semester-final with solutions','https://faculty.ksu.edu.sa/sites/default/files/math2541431-32-i_semester-finalasolution.pdf','MATH 254 final exam with solutions','https://faculty.ksu.edu.sa/sites/default/files/math2541431-32-i_semester-finalasolution.pdf','Exam','English','Official King Saud University faculty-hosted differential-equations final examination with complete solutions (1431-32 semester).'),
 ('Global','global','GA','IMO;problems database;olympiad','A','International Mathematical Olympiad','IMO official problems database','https://www.imo-official.org/problems.aspx','IMO problems database','https://www.imo-official.org/problems.aspx','Exam archive','English','Official IMO problems database covering all International Mathematical Olympiad problems by year with links to results.'),
 ('Global','global','GA','STEM olympiad;past papers','C','International STEM Olympiad','STEM Olympiad past papers','https://stemolympiad.org/gf/past_papers/','Past papers','https://stemolympiad.org/gf/past_papers/','Exam archive','English','Organiser-hosted past-paper collection for the international STEM Olympiad; openly accessible after live verification.'),
 ('Global','global','GA','olympiad training;free books;index','C','OmegaLearn curated index','OmegaLearn free olympiad books index','https://www.omegalearn.org/books','Free olympiad and competition books index','https://www.omegalearn.org/books','Gateway','English','Widely-used curated index linking legally free olympiad-training books and handouts; retained as discovery gateway.'),
 ('Global','global','DM','computer science;video courses;index','C','Developer-Y curated GitHub index','CS video courses curated index','https://github.com/Developer-Y/cs-video-courses','Curated computer-science video-course index','https://github.com/Developer-Y/cs-video-courses','Gateway','English','Community-maintained index of free university CS courses including discrete-mathematics lecture series; retained as discovery gateway.'),
]


def main()->None:
    known=set()
    for p in DATA.glob('*.csv'):
        with p.open(newline='',encoding='utf-8') as h:
            for r in csv.DictReader(h):
                if r.get('resource_url'): known.add(r['resource_url'].strip().lower())
    counts={}
    skipped=set()
    for row in R:
        if row[8].strip().lower() in known:
            skipped.add(row[8]); continue
        slug=row[1]
        out=DATA/f'{slug}_telegram_intake_verified_resources.csv'
        new=out.parent/out.name
        rec={'country':row[0],'track':row[2],'topic_tags':row[3],'priority':row[4],'source_type':row[5],'source_title':row[6],'source_url':row[7],'resource_title':row[8],'resource_url':row[9],'resource_class':row[10],'language':row[11],'notes':row[12],'access_model':FREE,'verification_status':VERIFIED,'free_resource':'Yes'}
        rows=[]
        if new.exists():
            with new.open(newline='',encoding='utf-8') as h: rows=list(csv.DictReader(h))
            rows=[r for r in rows if r['resource_url'].strip().lower()!=rec['resource_url'].strip().lower()]
        rows.append(rec)
        with new.open('w',newline='',encoding='utf-8') as h:
            w=csv.DictWriter(h,fieldnames=COLS); w.writeheader(); w.writerows(rows)
        counts[slug]=len(rows)
    print(f'Wrote tranches: {counts} ({sum(counts.values())} rows total)')
    if skipped: print('SKIPPED duplicates:',skipped)


if __name__=='__main__': main()
