/* Signal Atlas data index: generated by scripts/build_catalog_index.py. Keep resource rows in lazy CSV chunks. */

export type CountryCatalogStat = { catalogCount: number; freeCount: number; caveatCount: number };

export const catalogCountryIndex: Record<string, CountryCatalogStat> = {
  "United States": {
    "catalogCount": 118,
    "freeCount": 118,
    "caveatCount": 3
  },
  "Canada": {
    "catalogCount": 130,
    "freeCount": 130,
    "caveatCount": 0
  },
  "France": {
    "catalogCount": 86,
    "freeCount": 86,
    "caveatCount": 3
  },
  "Afghanistan": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Albania": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 1
  },
  "Algeria": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Antigua and Barbuda": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Australia": {
    "catalogCount": 109,
    "freeCount": 109,
    "caveatCount": 0
  },
  "New Zealand": {
    "catalogCount": 39,
    "freeCount": 39,
    "caveatCount": 0
  },
  "Japan": {
    "catalogCount": 100,
    "freeCount": 100,
    "caveatCount": 0
  },
  "Argentina": {
    "catalogCount": 3,
    "freeCount": 3,
    "caveatCount": 0
  },
  "Armenia": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 1
  },
  "Azerbaijan": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Bahrain": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Bangladesh": {
    "catalogCount": 4,
    "freeCount": 4,
    "caveatCount": 0
  },
  "Barbados": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Belarus": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Belgium": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Belize": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Benin": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Bhutan": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Bolivia": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Bosnia and Herzegovina": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 1
  },
  "Botswana": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Brazil": {
    "catalogCount": 3,
    "freeCount": 3,
    "caveatCount": 0
  },
  "Brunei": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Bulgaria": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Burkina Faso": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Cambodia": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Cameroon": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Central African Republic": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Chile": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "China": {
    "catalogCount": 3,
    "freeCount": 3,
    "caveatCount": 1
  },
  "Colombia": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Comoros": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Congo": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Costa Rica": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Côte d’Ivoire": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Croatia": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Cuba": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Cyprus": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 1
  },
  "Czechia": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Democratic Republic of the Congo": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Denmark": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Dominica": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Dominican Republic": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Ecuador": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Egypt": {
    "catalogCount": 5,
    "freeCount": 5,
    "caveatCount": 0
  },
  "El Salvador": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 1
  },
  "Estonia": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Eswatini": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Ethiopia": {
    "catalogCount": 3,
    "freeCount": 3,
    "caveatCount": 0
  },
  "Sweden": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Finland": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Fiji": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "United Kingdom": {
    "catalogCount": 149,
    "freeCount": 149,
    "caveatCount": 0
  },
  "Global": {
    "catalogCount": 6,
    "freeCount": 6,
    "caveatCount": 1
  },
  "Germany": {
    "catalogCount": 102,
    "freeCount": 102,
    "caveatCount": 0
  },
  "Gabon": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Gambia": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Liberia": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Georgia": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 1
  },
  "Ghana": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Greece": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Grenada": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Guatemala": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Guinea": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Guyana": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Haiti": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Honduras": {
    "catalogCount": 4,
    "freeCount": 4,
    "caveatCount": 0
  },
  "Hungary": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Republic of Korea": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Singapore": {
    "catalogCount": 5,
    "freeCount": 5,
    "caveatCount": 1
  },
  "South Africa": {
    "catalogCount": 150,
    "freeCount": 150,
    "caveatCount": 1
  },
  "India": {
    "catalogCount": 1551,
    "freeCount": 1551,
    "caveatCount": 0
  },
  "Indonesia": {
    "catalogCount": 46,
    "freeCount": 46,
    "caveatCount": 0
  },
  "Iran": {
    "catalogCount": 6,
    "freeCount": 6,
    "caveatCount": 0
  },
  "Iraq": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Israel": {
    "catalogCount": 9,
    "freeCount": 9,
    "caveatCount": 0
  },
  "Italy": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Jamaica": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Jordan": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Kazakhstan": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Kenya": {
    "catalogCount": 7,
    "freeCount": 7,
    "caveatCount": 0
  },
  "Kiribati": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Kuwait": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Kyrgyzstan": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Latvia": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Lebanon": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Lesotho": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Libya": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Lithuania": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Madagascar": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Malawi": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Malaysia": {
    "catalogCount": 101,
    "freeCount": 101,
    "caveatCount": 0
  },
  "Maldives": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Mali": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Mauritania": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Mauritius": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Mexico": {
    "catalogCount": 3,
    "freeCount": 3,
    "caveatCount": 0
  },
  "Republic of Moldova": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Mongolia": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Montenegro": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Morocco": {
    "catalogCount": 3,
    "freeCount": 3,
    "caveatCount": 0
  },
  "Mozambique": {
    "catalogCount": 3,
    "freeCount": 3,
    "caveatCount": 0
  },
  "Myanmar": {
    "catalogCount": 4,
    "freeCount": 4,
    "caveatCount": 0
  },
  "Namibia": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Nepal": {
    "catalogCount": 9,
    "freeCount": 9,
    "caveatCount": 0
  },
  "Netherlands": {
    "catalogCount": 81,
    "freeCount": 81,
    "caveatCount": 0
  },
  "Ireland": {
    "catalogCount": 4,
    "freeCount": 4,
    "caveatCount": 1
  },
  "Austria": {
    "catalogCount": 3,
    "freeCount": 3,
    "caveatCount": 0
  },
  "Niger": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Nigeria": {
    "catalogCount": 404,
    "freeCount": 404,
    "caveatCount": 0
  },
  "North Macedonia": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 1
  },
  "Norway": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Oman": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Pakistan": {
    "catalogCount": 48,
    "freeCount": 48,
    "caveatCount": 0
  },
  "Panama": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Papua New Guinea": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Paraguay": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 1
  },
  "Peru": {
    "catalogCount": 3,
    "freeCount": 3,
    "caveatCount": 0
  },
  "Philippines": {
    "catalogCount": 15,
    "freeCount": 15,
    "caveatCount": 0
  },
  "Poland": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Portugal": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Qatar": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Romania": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Russia": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Rwanda": {
    "catalogCount": 18,
    "freeCount": 18,
    "caveatCount": 0
  },
  "Saint Kitts and Nevis": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Saint Lucia": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Saint Vincent and the Grenadines": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Samoa": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Saudi Arabia": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Senegal": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Serbia": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Sierra Leone": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Slovakia": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Slovenia": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Solomon Islands": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Spain": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Sri Lanka": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Switzerland": {
    "catalogCount": 3,
    "freeCount": 3,
    "caveatCount": 0
  },
  "Syria": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Tajikistan": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Tanzania": {
    "catalogCount": 4,
    "freeCount": 4,
    "caveatCount": 0
  },
  "Thailand": {
    "catalogCount": 87,
    "freeCount": 87,
    "caveatCount": 0
  },
  "Timor-Leste": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Togo": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Tonga": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Trinidad and Tobago": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Tunisia": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Türkiye": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Uganda": {
    "catalogCount": 4,
    "freeCount": 4,
    "caveatCount": 0
  },
  "Ukraine": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "United Arab Emirates": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Uzbekistan": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Venezuela": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Viet Nam": {
    "catalogCount": 4,
    "freeCount": 4,
    "caveatCount": 0
  },
  "Zambia": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Zimbabwe": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  }
};

export const lazyChunksByCountry: Record<string, string[]> = {
  "Afghanistan": [
    "afghanistan_expansion_verified_resources.csv"
  ],
  "Albania": [
    "albania_expansion_verified_resources.csv"
  ],
  "Algeria": [
    "algeria_expansion_verified_resources.csv"
  ],
  "Antigua and Barbuda": [
    "antigua_and_barbuda_expansion_verified_resources.csv"
  ],
  "Argentina": [
    "argentina_expansion_verified_resources.csv"
  ],
  "Armenia": [
    "armenia_expansion_verified_resources.csv"
  ],
  "Australia": [
    "archive_depth_resources.csv",
    "australia_amt_enrichment_verified_resources.csv",
    "australia_amt_verified_resources.csv",
    "australia_nesa_2014_mg_verified_resources.csv",
    "australia_nesa_2015_ext_verified_resources.csv",
    "australia_nesa_2015_verified_resources.csv",
    "australia_nesa_2016_2019_verified_resources.csv",
    "australia_nesa_2020_2023_verified_resources.csv",
    "australia_qcaa_2023_2025_verified_resources.csv",
    "australia_qcaa_2025_verified_resources.csv",
    "australia_scsa_2022_2025_verified_resources.csv",
    "australia_telegram_intake_verified_resources.csv",
    "australia_vcaa_2023_2025_verified_resources.csv",
    "australia_vcaa_guides_verified_resources.csv"
  ],
  "Azerbaijan": [
    "azerbaijan_expansion_verified_resources.csv"
  ],
  "Bahrain": [
    "bahrain_expansion_verified_resources.csv"
  ],
  "Bangladesh": [
    "bangladesh_expansion_verified_resources.csv"
  ],
  "Barbados": [
    "barbados_expansion_verified_resources.csv"
  ],
  "Belarus": [
    "belarus_expansion_verified_resources.csv"
  ],
  "Belgium": [
    "belgium_expansion_verified_resources.csv"
  ],
  "Belize": [
    "belize_expansion_verified_resources.csv"
  ],
  "Benin": [
    "benin_expansion_verified_resources.csv"
  ],
  "Bhutan": [
    "bhutan_expansion_verified_resources.csv"
  ],
  "Bolivia": [
    "bolivia_expansion_verified_resources.csv"
  ],
  "Bosnia and Herzegovina": [
    "bosnia_and_herzegovina_expansion_verified_resources.csv"
  ],
  "Botswana": [
    "botswana_expansion_verified_resources.csv"
  ],
  "Brazil": [
    "brazil_expansion_verified_resources.csv"
  ],
  "Brunei": [
    "brunei_expansion_verified_resources.csv"
  ],
  "Bulgaria": [
    "bulgaria_expansion_verified_resources.csv"
  ],
  "Burkina Faso": [
    "burkina_faso_expansion_verified_resources.csv"
  ],
  "Cambodia": [
    "cambodia_expansion_verified_resources.csv"
  ],
  "Cameroon": [
    "cameroon_expansion_verified_resources.csv"
  ],
  "Canada": [
    "active_country_depth_resources.csv",
    "canada_cemc_bcc_2025_verified_resources.csv",
    "canada_cemc_verified_resources.csv",
    "canada_telegram_intake_verified_resources.csv",
    "four_country_depth_resources.csv"
  ],
  "Central African Republic": [
    "central_african_republic_expansion_verified_resources.csv"
  ],
  "Chile": [
    "chile_expansion_verified_resources.csv"
  ],
  "China": [
    "china_telegram_intake_verified_resources.csv"
  ],
  "Colombia": [
    "colombia_expansion_verified_resources.csv"
  ],
  "Comoros": [
    "comoros_expansion_verified_resources.csv"
  ],
  "Congo": [
    "congo_expansion_verified_resources.csv"
  ],
  "Costa Rica": [
    "costa_rica_expansion_verified_resources.csv"
  ],
  "Croatia": [
    "croatia_expansion_verified_resources.csv"
  ],
  "Cuba": [
    "cuba_expansion_verified_resources.csv"
  ],
  "Cyprus": [
    "cyprus_expansion_verified_resources.csv"
  ],
  "Czechia": [
    "czechia_expansion_verified_resources.csv"
  ],
  "Côte d’Ivoire": [
    "cote_divoire_expansion_verified_resources.csv"
  ],
  "Democratic Republic of the Congo": [
    "democratic_republic_of_the_congo_expansion_verified_resources.csv"
  ],
  "Denmark": [
    "denmark_expansion_verified_resources.csv"
  ],
  "Dominica": [
    "dominica_expansion_verified_resources.csv"
  ],
  "Dominican Republic": [
    "dominican_republic_expansion_verified_resources.csv"
  ],
  "Ecuador": [
    "ecuador_expansion_verified_resources.csv"
  ],
  "Egypt": [
    "egypt_expansion_verified_resources.csv"
  ],
  "El Salvador": [
    "el_salvador_expansion_verified_resources.csv"
  ],
  "Estonia": [
    "estonia_expansion_verified_resources.csv"
  ],
  "Eswatini": [
    "eswatini_expansion_verified_resources.csv"
  ],
  "Ethiopia": [
    "ethiopia_expansion_verified_resources.csv"
  ],
  "Fiji": [
    "fiji_expansion_verified_resources.csv"
  ],
  "Finland": [
    "finland_expansion_verified_resources.csv"
  ],
  "France": [
    "active_country_depth_resources.csv",
    "france_ccinp_verified_resources.csv"
  ],
  "Gabon": [
    "gabon_expansion_verified_resources.csv"
  ],
  "Gambia": [
    "gambia_expansion_verified_resources.csv"
  ],
  "Georgia": [
    "georgia_expansion_verified_resources.csv"
  ],
  "Germany": [
    "germany_bwinf_verified_resources.csv"
  ],
  "Ghana": [
    "ghana_expansion_verified_resources.csv"
  ],
  "Global": [
    "global_telegram_intake_verified_resources.csv"
  ],
  "Greece": [
    "greece_expansion_verified_resources.csv"
  ],
  "Grenada": [
    "grenada_expansion_verified_resources.csv"
  ],
  "Guatemala": [
    "guatemala_expansion_verified_resources.csv"
  ],
  "Guinea": [
    "guinea_expansion_verified_resources.csv"
  ],
  "Guyana": [
    "guyana_expansion_verified_resources.csv"
  ],
  "Haiti": [
    "haiti_expansion_verified_resources.csv"
  ],
  "Honduras": [
    "honduras_expansion_verified_resources.csv"
  ],
  "Hungary": [
    "hungary_expansion_verified_resources.csv"
  ],
  "India": [
    "india_gate_verified_resources.csv",
    "india_telegram_intake_verified_resources.csv",
    "india_tifr_verified_resources.csv"
  ],
  "Indonesia": [
    "indonesia_binus_icpc2020_verified_resources.csv",
    "indonesia_binus_icpc2021_verified_resources.csv",
    "indonesia_binus_icpc2022_verified_resources.csv",
    "indonesia_expansion_verified_resources.csv",
    "indonesia_ioi2022_verified_resources.csv"
  ],
  "Iran": [
    "iran_expansion_verified_resources.csv"
  ],
  "Iraq": [
    "iraq_expansion_verified_resources.csv"
  ],
  "Israel": [
    "israel_telegram_intake_verified_resources.csv"
  ],
  "Italy": [
    "italy_telegram_intake_verified_resources.csv"
  ],
  "Jamaica": [
    "jamaica_telegram_intake_verified_resources.csv"
  ],
  "Japan": [
    "archive_depth_resources.csv",
    "japan_joi_verified_resources.csv",
    "japan_mext_verified_resources.csv"
  ],
  "Jordan": [
    "jordan_expansion_verified_resources.csv"
  ],
  "Kazakhstan": [
    "kazakhstan_expansion_verified_resources.csv"
  ],
  "Kenya": [
    "kenya_must_verified_resources.csv",
    "kenya_university_math_verified_resources.csv"
  ],
  "Kiribati": [
    "kiribati_expansion_verified_resources.csv"
  ],
  "Kuwait": [
    "kuwait_expansion_verified_resources.csv"
  ],
  "Kyrgyzstan": [
    "kyrgyzstan_expansion_verified_resources.csv"
  ],
  "Latvia": [
    "latvia_expansion_verified_resources.csv"
  ],
  "Lebanon": [
    "lebanon_telegram_intake_verified_resources.csv"
  ],
  "Lesotho": [
    "lesotho_expansion_verified_resources.csv"
  ],
  "Liberia": [
    "liberia_expansion_verified_resources.csv"
  ],
  "Libya": [
    "libya_expansion_verified_resources.csv"
  ],
  "Lithuania": [
    "lithuania_expansion_verified_resources.csv"
  ],
  "Madagascar": [
    "madagascar_expansion_verified_resources.csv"
  ],
  "Malawi": [
    "malawi_expansion_verified_resources.csv"
  ],
  "Malaysia": [
    "malaysia_emos_imas2025_verified_resources.csv",
    "malaysia_emos_som2025_verified_resources.csv",
    "malaysia_imonst_verified_resources.csv",
    "malaysia_mcc2025_verified_resources.csv",
    "malaysia_mco2015_solutions_verified_resources.csv",
    "malaysia_mco_2023_verified_resources.csv",
    "malaysia_mco_2024_2025_verified_resources.csv",
    "malaysia_mco_codeforces_verified_resources.csv",
    "malaysia_mco_direct_tasks_verified_resources.csv",
    "malaysia_mco_verified_resources.csv",
    "malaysia_peninsula_dcs1123_verified_resources.csv",
    "malaysia_uitm_mo_verified_resources.csv"
  ],
  "Maldives": [
    "maldives_expansion_verified_resources.csv"
  ],
  "Mali": [
    "mali_expansion_verified_resources.csv"
  ],
  "Mauritania": [
    "mauritania_expansion_verified_resources.csv"
  ],
  "Mauritius": [
    "mauritius_expansion_verified_resources.csv"
  ],
  "Mexico": [
    "mexico_expansion_verified_resources.csv"
  ],
  "Mongolia": [
    "mongolia_expansion_verified_resources.csv"
  ],
  "Montenegro": [
    "montenegro_expansion_verified_resources.csv"
  ],
  "Morocco": [
    "morocco_expansion_verified_resources.csv"
  ],
  "Mozambique": [
    "mozambique_expansion_verified_resources.csv"
  ],
  "Myanmar": [
    "myanmar_expansion_verified_resources.csv"
  ],
  "Namibia": [
    "namibia_expansion_verified_resources.csv"
  ],
  "Nepal": [
    "nepal_lec_verified_resources.csv",
    "nepal_mano_verified_resources.csv"
  ],
  "Netherlands": [
    "netherlands_math_olympiad_verified_resources.csv"
  ],
  "New Zealand": [
    "archive_depth_resources.csv",
    "new_zealand_telegram_intake_verified_resources.csv"
  ],
  "Niger": [
    "niger_expansion_verified_resources.csv"
  ],
  "Nigeria": [
    "nigeria_telegram_intake_verified_resources.csv",
    "nigeria_waec_verified_resources.csv"
  ],
  "North Macedonia": [
    "north_macedonia_expansion_verified_resources.csv"
  ],
  "Norway": [
    "norway_expansion_verified_resources.csv"
  ],
  "Oman": [
    "oman_expansion_verified_resources.csv"
  ],
  "Pakistan": [
    "pakistan_expansion_verified_resources.csv",
    "pakistan_gcu_verified_resources.csv",
    "pakistan_giki_verified_resources.csv",
    "pakistan_iba_verified_resources.csv",
    "pakistan_pu_verified_resources.csv",
    "pakistan_university_followup_verified_resources.csv"
  ],
  "Panama": [
    "panama_expansion_verified_resources.csv"
  ],
  "Papua New Guinea": [
    "papua_new_guinea_expansion_verified_resources.csv"
  ],
  "Paraguay": [
    "paraguay_expansion_verified_resources.csv"
  ],
  "Peru": [
    "peru_expansion_verified_resources.csv"
  ],
  "Philippines": [
    "philippines_expansion_verified_resources.csv",
    "philippines_noiph2020_eliminations_verified_resources.csv",
    "philippines_noiph2020_gym_verified_resources.csv",
    "philippines_noiph_pdf_verified_resources.csv"
  ],
  "Poland": [
    "poland_expansion_verified_resources.csv"
  ],
  "Portugal": [
    "portugal_expansion_verified_resources.csv"
  ],
  "Qatar": [
    "qatar_expansion_verified_resources.csv"
  ],
  "Republic of Moldova": [
    "moldova_expansion_verified_resources.csv"
  ],
  "Romania": [
    "romania_expansion_verified_resources.csv"
  ],
  "Russia": [
    "russia_expansion_verified_resources.csv"
  ],
  "Rwanda": [
    "rwanda_nesa_verified_resources.csv"
  ],
  "Saint Kitts and Nevis": [
    "saint_kitts_and_nevis_expansion_verified_resources.csv"
  ],
  "Saint Lucia": [
    "saint_lucia_expansion_verified_resources.csv"
  ],
  "Saint Vincent and the Grenadines": [
    "saint_vincent_and_the_grenadines_expansion_verified_resources.csv"
  ],
  "Samoa": [
    "samoa_expansion_verified_resources.csv"
  ],
  "Saudi Arabia": [
    "saudi_arabia_telegram_intake_verified_resources.csv"
  ],
  "Senegal": [
    "senegal_expansion_verified_resources.csv"
  ],
  "Serbia": [
    "serbia_expansion_verified_resources.csv"
  ],
  "Sierra Leone": [
    "sierra_leone_expansion_verified_resources.csv"
  ],
  "Singapore": [
    "singapore_official_math_verified_resources.csv"
  ],
  "Slovakia": [
    "slovakia_expansion_verified_resources.csv"
  ],
  "Slovenia": [
    "slovenia_expansion_verified_resources.csv"
  ],
  "Solomon Islands": [
    "solomon_islands_expansion_verified_resources.csv"
  ],
  "South Africa": [
    "south_africa_foundation_math_verified_resources.csv",
    "south_africa_junior_math_verified_resources.csv",
    "south_africa_samf_verified_resources.csv",
    "south_africa_telegram_intake_verified_resources.csv",
    "south_africa_uct_2018_verified_resources.csv",
    "south_africa_uj_math_followup_verified_resources.csv",
    "south_africa_uj_math_verified_resources.csv",
    "south_africa_upmc_verified_resources.csv",
    "south_africa_wits_verified_resources.csv"
  ],
  "Spain": [
    "spain_expansion_verified_resources.csv"
  ],
  "Sri Lanka": [
    "sri_lanka_ousl_verified_resources.csv"
  ],
  "Switzerland": [
    "switzerland_expansion_verified_resources.csv"
  ],
  "Syria": [
    "syria_expansion_verified_resources.csv"
  ],
  "Tajikistan": [
    "tajikistan_expansion_verified_resources.csv"
  ],
  "Tanzania": [
    "tanzania_necta_verified_resources.csv"
  ],
  "Thailand": [
    "thailand_chula_2007_practice_verified_resources.csv",
    "thailand_chula_icpc2024_editorials_verified_resources.csv",
    "thailand_chula_verified_resources.csv",
    "thailand_icpc_bangkok2025_verified_resources.csv",
    "thailand_kku_2009_homework_verified_resources.csv",
    "thailand_kku_2010_assessments_verified_resources.csv",
    "thailand_kku_2010_quizzes_verified_resources.csv",
    "thailand_kku_2011_assessments_verified_resources.csv",
    "thailand_kku_2012_homework_verified_resources.csv",
    "thailand_kku_2014_2013_exams_verified_resources.csv",
    "thailand_kku_2014_verified_resources.csv",
    "thailand_kku_discrete_snapshot_verified_resources.csv",
    "thailand_kku_dm_verified_resources.csv",
    "thailand_mahidol_muic_math_verified_resources.csv",
    "thailand_muic_verified_resources.csv",
    "thailand_siit_verified_resources.csv"
  ],
  "Timor-Leste": [
    "timor_leste_expansion_verified_resources.csv"
  ],
  "Togo": [
    "togo_expansion_verified_resources.csv"
  ],
  "Tonga": [
    "tonga_expansion_verified_resources.csv"
  ],
  "Trinidad and Tobago": [
    "trinidad_and_tobago_expansion_verified_resources.csv"
  ],
  "Tunisia": [
    "tunisia_expansion_verified_resources.csv"
  ],
  "Türkiye": [
    "turkiye_expansion_verified_resources.csv"
  ],
  "Uganda": [
    "uganda_uneb_verified_resources.csv"
  ],
  "Ukraine": [
    "ukraine_expansion_verified_resources.csv"
  ],
  "United Arab Emirates": [
    "united_arab_emirates_expansion_verified_resources.csv"
  ],
  "United Kingdom": [
    "united_kingdom_bmo_verified_resources.csv",
    "united_kingdom_telegram_intake_verified_resources.csv"
  ],
  "United States": [
    "active_country_depth_resources.csv",
    "united_states_telegram_intake_verified_resources.csv",
    "united_states_usaco_2026_verified_resources.csv",
    "united_states_usaco_verified_resources.csv"
  ],
  "Uzbekistan": [
    "uzbekistan_expansion_verified_resources.csv"
  ],
  "Venezuela": [
    "venezuela_expansion_verified_resources.csv"
  ],
  "Viet Nam": [
    "vietnam_expansion_verified_resources.csv"
  ],
  "Zambia": [
    "zambia_expansion_verified_resources.csv"
  ],
  "Zimbabwe": [
    "zimbabwe_buse_verified_resources.csv"
  ]
};

export const csvChunkLoaders: Record<string, () => Promise<{ default: string }>> = {
  "active_country_depth_resources.csv": () => import("@/data/active_country_depth_resources.csv?raw"),
  "afghanistan_expansion_verified_resources.csv": () => import("@/data/afghanistan_expansion_verified_resources.csv?raw"),
  "albania_expansion_verified_resources.csv": () => import("@/data/albania_expansion_verified_resources.csv?raw"),
  "algeria_expansion_verified_resources.csv": () => import("@/data/algeria_expansion_verified_resources.csv?raw"),
  "antigua_and_barbuda_expansion_verified_resources.csv": () => import("@/data/antigua_and_barbuda_expansion_verified_resources.csv?raw"),
  "archive_depth_resources.csv": () => import("@/data/archive_depth_resources.csv?raw"),
  "argentina_expansion_verified_resources.csv": () => import("@/data/argentina_expansion_verified_resources.csv?raw"),
  "armenia_expansion_verified_resources.csv": () => import("@/data/armenia_expansion_verified_resources.csv?raw"),
  "australia_amt_enrichment_verified_resources.csv": () => import("@/data/australia_amt_enrichment_verified_resources.csv?raw"),
  "australia_amt_verified_resources.csv": () => import("@/data/australia_amt_verified_resources.csv?raw"),
  "australia_nesa_2014_mg_verified_resources.csv": () => import("@/data/australia_nesa_2014_mg_verified_resources.csv?raw"),
  "australia_nesa_2015_ext_verified_resources.csv": () => import("@/data/australia_nesa_2015_ext_verified_resources.csv?raw"),
  "australia_nesa_2015_verified_resources.csv": () => import("@/data/australia_nesa_2015_verified_resources.csv?raw"),
  "australia_nesa_2016_2019_verified_resources.csv": () => import("@/data/australia_nesa_2016_2019_verified_resources.csv?raw"),
  "australia_nesa_2020_2023_verified_resources.csv": () => import("@/data/australia_nesa_2020_2023_verified_resources.csv?raw"),
  "australia_qcaa_2023_2025_verified_resources.csv": () => import("@/data/australia_qcaa_2023_2025_verified_resources.csv?raw"),
  "australia_qcaa_2025_verified_resources.csv": () => import("@/data/australia_qcaa_2025_verified_resources.csv?raw"),
  "australia_scsa_2022_2025_verified_resources.csv": () => import("@/data/australia_scsa_2022_2025_verified_resources.csv?raw"),
  "australia_scsa_verified_resources.csv": () => import("@/data/australia_scsa_verified_resources.csv?raw"),
  "australia_telegram_intake_verified_resources.csv": () => import("@/data/australia_telegram_intake_verified_resources.csv?raw"),
  "australia_vcaa_2023_2025_verified_resources.csv": () => import("@/data/australia_vcaa_2023_2025_verified_resources.csv?raw"),
  "australia_vcaa_guides_verified_resources.csv": () => import("@/data/australia_vcaa_guides_verified_resources.csv?raw"),
  "austria_oemo_verified_resources.csv": () => import("@/data/austria_oemo_verified_resources.csv?raw"),
  "azerbaijan_expansion_verified_resources.csv": () => import("@/data/azerbaijan_expansion_verified_resources.csv?raw"),
  "bahrain_expansion_verified_resources.csv": () => import("@/data/bahrain_expansion_verified_resources.csv?raw"),
  "bangladesh_expansion_verified_resources.csv": () => import("@/data/bangladesh_expansion_verified_resources.csv?raw"),
  "barbados_expansion_verified_resources.csv": () => import("@/data/barbados_expansion_verified_resources.csv?raw"),
  "belarus_expansion_verified_resources.csv": () => import("@/data/belarus_expansion_verified_resources.csv?raw"),
  "belgium_expansion_verified_resources.csv": () => import("@/data/belgium_expansion_verified_resources.csv?raw"),
  "belgium_vwo_verified_resources.csv": () => import("@/data/belgium_vwo_verified_resources.csv?raw"),
  "belize_expansion_verified_resources.csv": () => import("@/data/belize_expansion_verified_resources.csv?raw"),
  "benin_expansion_verified_resources.csv": () => import("@/data/benin_expansion_verified_resources.csv?raw"),
  "bhutan_expansion_verified_resources.csv": () => import("@/data/bhutan_expansion_verified_resources.csv?raw"),
  "bolivia_expansion_verified_resources.csv": () => import("@/data/bolivia_expansion_verified_resources.csv?raw"),
  "bosnia_and_herzegovina_expansion_verified_resources.csv": () => import("@/data/bosnia_and_herzegovina_expansion_verified_resources.csv?raw"),
  "botswana_expansion_verified_resources.csv": () => import("@/data/botswana_expansion_verified_resources.csv?raw"),
  "brazil_expansion_verified_resources.csv": () => import("@/data/brazil_expansion_verified_resources.csv?raw"),
  "brazil_obm_verified_resources.csv": () => import("@/data/brazil_obm_verified_resources.csv?raw"),
  "brunei_expansion_verified_resources.csv": () => import("@/data/brunei_expansion_verified_resources.csv?raw"),
  "bulgaria_expansion_verified_resources.csv": () => import("@/data/bulgaria_expansion_verified_resources.csv?raw"),
  "burkina_faso_expansion_verified_resources.csv": () => import("@/data/burkina_faso_expansion_verified_resources.csv?raw"),
  "cambodia_expansion_verified_resources.csv": () => import("@/data/cambodia_expansion_verified_resources.csv?raw"),
  "cameroon_expansion_verified_resources.csv": () => import("@/data/cameroon_expansion_verified_resources.csv?raw"),
  "canada_cemc_bcc_2025_verified_resources.csv": () => import("@/data/canada_cemc_bcc_2025_verified_resources.csv?raw"),
  "canada_cemc_verified_resources.csv": () => import("@/data/canada_cemc_verified_resources.csv?raw"),
  "canada_telegram_intake_verified_resources.csv": () => import("@/data/canada_telegram_intake_verified_resources.csv?raw"),
  "central_african_republic_expansion_verified_resources.csv": () => import("@/data/central_african_republic_expansion_verified_resources.csv?raw"),
  "chile_expansion_verified_resources.csv": () => import("@/data/chile_expansion_verified_resources.csv?raw"),
  "china_ccf_gesp_verified_resources.csv": () => import("@/data/china_ccf_gesp_verified_resources.csv?raw"),
  "china_telegram_intake_verified_resources.csv": () => import("@/data/china_telegram_intake_verified_resources.csv?raw"),
  "colombia_expansion_verified_resources.csv": () => import("@/data/colombia_expansion_verified_resources.csv?raw"),
  "comoros_expansion_verified_resources.csv": () => import("@/data/comoros_expansion_verified_resources.csv?raw"),
  "congo_expansion_verified_resources.csv": () => import("@/data/congo_expansion_verified_resources.csv?raw"),
  "costa_rica_expansion_verified_resources.csv": () => import("@/data/costa_rica_expansion_verified_resources.csv?raw"),
  "cote_divoire_expansion_verified_resources.csv": () => import("@/data/cote_divoire_expansion_verified_resources.csv?raw"),
  "croatia_expansion_verified_resources.csv": () => import("@/data/croatia_expansion_verified_resources.csv?raw"),
  "cuba_expansion_verified_resources.csv": () => import("@/data/cuba_expansion_verified_resources.csv?raw"),
  "cyprus_expansion_verified_resources.csv": () => import("@/data/cyprus_expansion_verified_resources.csv?raw"),
  "czechia_expansion_verified_resources.csv": () => import("@/data/czechia_expansion_verified_resources.csv?raw"),
  "czechia_mo_verified_resources.csv": () => import("@/data/czechia_mo_verified_resources.csv?raw"),
  "democratic_republic_of_the_congo_expansion_verified_resources.csv": () => import("@/data/democratic_republic_of_the_congo_expansion_verified_resources.csv?raw"),
  "denmark_expansion_verified_resources.csv": () => import("@/data/denmark_expansion_verified_resources.csv?raw"),
  "dominica_expansion_verified_resources.csv": () => import("@/data/dominica_expansion_verified_resources.csv?raw"),
  "dominican_republic_expansion_verified_resources.csv": () => import("@/data/dominican_republic_expansion_verified_resources.csv?raw"),
  "ecuador_expansion_verified_resources.csv": () => import("@/data/ecuador_expansion_verified_resources.csv?raw"),
  "egypt_expansion_verified_resources.csv": () => import("@/data/egypt_expansion_verified_resources.csv?raw"),
  "el_salvador_expansion_verified_resources.csv": () => import("@/data/el_salvador_expansion_verified_resources.csv?raw"),
  "estonia_expansion_verified_resources.csv": () => import("@/data/estonia_expansion_verified_resources.csv?raw"),
  "eswatini_expansion_verified_resources.csv": () => import("@/data/eswatini_expansion_verified_resources.csv?raw"),
  "ethiopia_expansion_verified_resources.csv": () => import("@/data/ethiopia_expansion_verified_resources.csv?raw"),
  "european_wave_resources.csv": () => import("@/data/european_wave_resources.csv?raw"),
  "fiji_expansion_verified_resources.csv": () => import("@/data/fiji_expansion_verified_resources.csv?raw"),
  "finland_expansion_verified_resources.csv": () => import("@/data/finland_expansion_verified_resources.csv?raw"),
  "four_country_depth_resources.csv": () => import("@/data/four_country_depth_resources.csv?raw"),
  "france_ccinp_verified_resources.csv": () => import("@/data/france_ccinp_verified_resources.csv?raw"),
  "free_resources.csv": () => import("@/data/free_resources.csv?raw"),
  "gabon_expansion_verified_resources.csv": () => import("@/data/gabon_expansion_verified_resources.csv?raw"),
  "gambia_expansion_verified_resources.csv": () => import("@/data/gambia_expansion_verified_resources.csv?raw"),
  "georgia_expansion_verified_resources.csv": () => import("@/data/georgia_expansion_verified_resources.csv?raw"),
  "germany_bwinf_verified_resources.csv": () => import("@/data/germany_bwinf_verified_resources.csv?raw"),
  "ghana_expansion_verified_resources.csv": () => import("@/data/ghana_expansion_verified_resources.csv?raw"),
  "global_telegram_intake_verified_resources.csv": () => import("@/data/global_telegram_intake_verified_resources.csv?raw"),
  "greece_expansion_verified_resources.csv": () => import("@/data/greece_expansion_verified_resources.csv?raw"),
  "grenada_expansion_verified_resources.csv": () => import("@/data/grenada_expansion_verified_resources.csv?raw"),
  "guatemala_expansion_verified_resources.csv": () => import("@/data/guatemala_expansion_verified_resources.csv?raw"),
  "guinea_expansion_verified_resources.csv": () => import("@/data/guinea_expansion_verified_resources.csv?raw"),
  "guyana_expansion_verified_resources.csv": () => import("@/data/guyana_expansion_verified_resources.csv?raw"),
  "haiti_expansion_verified_resources.csv": () => import("@/data/haiti_expansion_verified_resources.csv?raw"),
  "honduras_expansion_verified_resources.csv": () => import("@/data/honduras_expansion_verified_resources.csv?raw"),
  "hungary_expansion_verified_resources.csv": () => import("@/data/hungary_expansion_verified_resources.csv?raw"),
  "important_country_resources.csv": () => import("@/data/important_country_resources.csv?raw"),
  "india_gate_verified_resources.csv": () => import("@/data/india_gate_verified_resources.csv?raw"),
  "india_telegram_intake_verified_resources.csv": () => import("@/data/india_telegram_intake_verified_resources.csv?raw"),
  "india_tifr_verified_resources.csv": () => import("@/data/india_tifr_verified_resources.csv?raw"),
  "indonesia_binus_icpc2020_verified_resources.csv": () => import("@/data/indonesia_binus_icpc2020_verified_resources.csv?raw"),
  "indonesia_binus_icpc2021_verified_resources.csv": () => import("@/data/indonesia_binus_icpc2021_verified_resources.csv?raw"),
  "indonesia_binus_icpc2022_verified_resources.csv": () => import("@/data/indonesia_binus_icpc2022_verified_resources.csv?raw"),
  "indonesia_expansion_verified_resources.csv": () => import("@/data/indonesia_expansion_verified_resources.csv?raw"),
  "indonesia_ioi2022_verified_resources.csv": () => import("@/data/indonesia_ioi2022_verified_resources.csv?raw"),
  "indonesia_osn_pdf_verified_resources.csv": () => import("@/data/indonesia_osn_pdf_verified_resources.csv?raw"),
  "indonesia_osn_solutions_verified_resources.csv": () => import("@/data/indonesia_osn_solutions_verified_resources.csv?raw"),
  "indonesia_toki_verified_resources.csv": () => import("@/data/indonesia_toki_verified_resources.csv?raw"),
  "iran_expansion_verified_resources.csv": () => import("@/data/iran_expansion_verified_resources.csv?raw"),
  "iraq_expansion_verified_resources.csv": () => import("@/data/iraq_expansion_verified_resources.csv?raw"),
  "israel_telegram_intake_verified_resources.csv": () => import("@/data/israel_telegram_intake_verified_resources.csv?raw"),
  "italy_math_olympiad_verified_resources.csv": () => import("@/data/italy_math_olympiad_verified_resources.csv?raw"),
  "italy_telegram_intake_verified_resources.csv": () => import("@/data/italy_telegram_intake_verified_resources.csv?raw"),
  "jamaica_telegram_intake_verified_resources.csv": () => import("@/data/jamaica_telegram_intake_verified_resources.csv?raw"),
  "japan_joi_verified_resources.csv": () => import("@/data/japan_joi_verified_resources.csv?raw"),
  "japan_mext_verified_resources.csv": () => import("@/data/japan_mext_verified_resources.csv?raw"),
  "jordan_expansion_verified_resources.csv": () => import("@/data/jordan_expansion_verified_resources.csv?raw"),
  "kazakhstan_expansion_verified_resources.csv": () => import("@/data/kazakhstan_expansion_verified_resources.csv?raw"),
  "kenya_must_verified_resources.csv": () => import("@/data/kenya_must_verified_resources.csv?raw"),
  "kenya_university_math_verified_resources.csv": () => import("@/data/kenya_university_math_verified_resources.csv?raw"),
  "kiribati_expansion_verified_resources.csv": () => import("@/data/kiribati_expansion_verified_resources.csv?raw"),
  "kuwait_expansion_verified_resources.csv": () => import("@/data/kuwait_expansion_verified_resources.csv?raw"),
  "kyrgyzstan_expansion_verified_resources.csv": () => import("@/data/kyrgyzstan_expansion_verified_resources.csv?raw"),
  "latvia_expansion_verified_resources.csv": () => import("@/data/latvia_expansion_verified_resources.csv?raw"),
  "lebanon_telegram_intake_verified_resources.csv": () => import("@/data/lebanon_telegram_intake_verified_resources.csv?raw"),
  "lesotho_expansion_verified_resources.csv": () => import("@/data/lesotho_expansion_verified_resources.csv?raw"),
  "liberia_expansion_verified_resources.csv": () => import("@/data/liberia_expansion_verified_resources.csv?raw"),
  "libya_expansion_verified_resources.csv": () => import("@/data/libya_expansion_verified_resources.csv?raw"),
  "lithuania_expansion_verified_resources.csv": () => import("@/data/lithuania_expansion_verified_resources.csv?raw"),
  "madagascar_expansion_verified_resources.csv": () => import("@/data/madagascar_expansion_verified_resources.csv?raw"),
  "malawi_expansion_verified_resources.csv": () => import("@/data/malawi_expansion_verified_resources.csv?raw"),
  "malaysia_beaver_english_verified_resources.csv": () => import("@/data/malaysia_beaver_english_verified_resources.csv?raw"),
  "malaysia_emos_imas2025_verified_resources.csv": () => import("@/data/malaysia_emos_imas2025_verified_resources.csv?raw"),
  "malaysia_emos_som2025_verified_resources.csv": () => import("@/data/malaysia_emos_som2025_verified_resources.csv?raw"),
  "malaysia_imonst_verified_resources.csv": () => import("@/data/malaysia_imonst_verified_resources.csv?raw"),
  "malaysia_mcc2025_verified_resources.csv": () => import("@/data/malaysia_mcc2025_verified_resources.csv?raw"),
  "malaysia_mco2015_solutions_verified_resources.csv": () => import("@/data/malaysia_mco2015_solutions_verified_resources.csv?raw"),
  "malaysia_mco_2023_verified_resources.csv": () => import("@/data/malaysia_mco_2023_verified_resources.csv?raw"),
  "malaysia_mco_2024_2025_verified_resources.csv": () => import("@/data/malaysia_mco_2024_2025_verified_resources.csv?raw"),
  "malaysia_mco_codeforces_verified_resources.csv": () => import("@/data/malaysia_mco_codeforces_verified_resources.csv?raw"),
  "malaysia_mco_direct_tasks_verified_resources.csv": () => import("@/data/malaysia_mco_direct_tasks_verified_resources.csv?raw"),
  "malaysia_mco_verified_resources.csv": () => import("@/data/malaysia_mco_verified_resources.csv?raw"),
  "malaysia_peninsula_dcs1123_verified_resources.csv": () => import("@/data/malaysia_peninsula_dcs1123_verified_resources.csv?raw"),
  "malaysia_uitm_mo_verified_resources.csv": () => import("@/data/malaysia_uitm_mo_verified_resources.csv?raw"),
  "maldives_expansion_verified_resources.csv": () => import("@/data/maldives_expansion_verified_resources.csv?raw"),
  "mali_expansion_verified_resources.csv": () => import("@/data/mali_expansion_verified_resources.csv?raw"),
  "mauritania_expansion_verified_resources.csv": () => import("@/data/mauritania_expansion_verified_resources.csv?raw"),
  "mauritius_expansion_verified_resources.csv": () => import("@/data/mauritius_expansion_verified_resources.csv?raw"),
  "mexico_expansion_verified_resources.csv": () => import("@/data/mexico_expansion_verified_resources.csv?raw"),
  "mexico_omm_canguro_verified_resources.csv": () => import("@/data/mexico_omm_canguro_verified_resources.csv?raw"),
  "moldova_expansion_verified_resources.csv": () => import("@/data/moldova_expansion_verified_resources.csv?raw"),
  "mongolia_expansion_verified_resources.csv": () => import("@/data/mongolia_expansion_verified_resources.csv?raw"),
  "montenegro_expansion_verified_resources.csv": () => import("@/data/montenegro_expansion_verified_resources.csv?raw"),
  "morocco_expansion_verified_resources.csv": () => import("@/data/morocco_expansion_verified_resources.csv?raw"),
  "mozambique_expansion_verified_resources.csv": () => import("@/data/mozambique_expansion_verified_resources.csv?raw"),
  "myanmar_expansion_verified_resources.csv": () => import("@/data/myanmar_expansion_verified_resources.csv?raw"),
  "namibia_expansion_verified_resources.csv": () => import("@/data/namibia_expansion_verified_resources.csv?raw"),
  "nepal_lec_verified_resources.csv": () => import("@/data/nepal_lec_verified_resources.csv?raw"),
  "nepal_mano_verified_resources.csv": () => import("@/data/nepal_mano_verified_resources.csv?raw"),
  "netherlands_math_olympiad_verified_resources.csv": () => import("@/data/netherlands_math_olympiad_verified_resources.csv?raw"),
  "new_zealand_nzqa_verified_resources.csv": () => import("@/data/new_zealand_nzqa_verified_resources.csv?raw"),
  "new_zealand_telegram_intake_verified_resources.csv": () => import("@/data/new_zealand_telegram_intake_verified_resources.csv?raw"),
  "next_european_wave_resources.csv": () => import("@/data/next_european_wave_resources.csv?raw"),
  "niger_expansion_verified_resources.csv": () => import("@/data/niger_expansion_verified_resources.csv?raw"),
  "nigeria_telegram_intake_verified_resources.csv": () => import("@/data/nigeria_telegram_intake_verified_resources.csv?raw"),
  "nigeria_waec_verified_resources.csv": () => import("@/data/nigeria_waec_verified_resources.csv?raw"),
  "north_macedonia_expansion_verified_resources.csv": () => import("@/data/north_macedonia_expansion_verified_resources.csv?raw"),
  "norway_expansion_verified_resources.csv": () => import("@/data/norway_expansion_verified_resources.csv?raw"),
  "oman_expansion_verified_resources.csv": () => import("@/data/oman_expansion_verified_resources.csv?raw"),
  "pakistan_expansion_verified_resources.csv": () => import("@/data/pakistan_expansion_verified_resources.csv?raw"),
  "pakistan_gcu_verified_resources.csv": () => import("@/data/pakistan_gcu_verified_resources.csv?raw"),
  "pakistan_giki_verified_resources.csv": () => import("@/data/pakistan_giki_verified_resources.csv?raw"),
  "pakistan_hec_etc_verified_resources.csv": () => import("@/data/pakistan_hec_etc_verified_resources.csv?raw"),
  "pakistan_iba_verified_resources.csv": () => import("@/data/pakistan_iba_verified_resources.csv?raw"),
  "pakistan_pu_verified_resources.csv": () => import("@/data/pakistan_pu_verified_resources.csv?raw"),
  "pakistan_university_followup_verified_resources.csv": () => import("@/data/pakistan_university_followup_verified_resources.csv?raw"),
  "panama_expansion_verified_resources.csv": () => import("@/data/panama_expansion_verified_resources.csv?raw"),
  "papua_new_guinea_expansion_verified_resources.csv": () => import("@/data/papua_new_guinea_expansion_verified_resources.csv?raw"),
  "paraguay_expansion_verified_resources.csv": () => import("@/data/paraguay_expansion_verified_resources.csv?raw"),
  "peru_expansion_verified_resources.csv": () => import("@/data/peru_expansion_verified_resources.csv?raw"),
  "philippines_expansion_verified_resources.csv": () => import("@/data/philippines_expansion_verified_resources.csv?raw"),
  "philippines_noiph2020_eliminations_verified_resources.csv": () => import("@/data/philippines_noiph2020_eliminations_verified_resources.csv?raw"),
  "philippines_noiph2020_gym_verified_resources.csv": () => import("@/data/philippines_noiph2020_gym_verified_resources.csv?raw"),
  "philippines_noiph_pdf_verified_resources.csv": () => import("@/data/philippines_noiph_pdf_verified_resources.csv?raw"),
  "poland_expansion_verified_resources.csv": () => import("@/data/poland_expansion_verified_resources.csv?raw"),
  "poland_om_verified_resources.csv": () => import("@/data/poland_om_verified_resources.csv?raw"),
  "portugal_expansion_verified_resources.csv": () => import("@/data/portugal_expansion_verified_resources.csv?raw"),
  "qatar_expansion_verified_resources.csv": () => import("@/data/qatar_expansion_verified_resources.csv?raw"),
  "republic_of_korea_kice_csat_verified_resources.csv": () => import("@/data/republic_of_korea_kice_csat_verified_resources.csv?raw"),
  "romania_expansion_verified_resources.csv": () => import("@/data/romania_expansion_verified_resources.csv?raw"),
  "russia_expansion_verified_resources.csv": () => import("@/data/russia_expansion_verified_resources.csv?raw"),
  "russia_fipi_advanced_math_verified_resources.csv": () => import("@/data/russia_fipi_advanced_math_verified_resources.csv?raw"),
  "rwanda_nesa_verified_resources.csv": () => import("@/data/rwanda_nesa_verified_resources.csv?raw"),
  "saint_kitts_and_nevis_expansion_verified_resources.csv": () => import("@/data/saint_kitts_and_nevis_expansion_verified_resources.csv?raw"),
  "saint_lucia_expansion_verified_resources.csv": () => import("@/data/saint_lucia_expansion_verified_resources.csv?raw"),
  "saint_vincent_and_the_grenadines_expansion_verified_resources.csv": () => import("@/data/saint_vincent_and_the_grenadines_expansion_verified_resources.csv?raw"),
  "samoa_expansion_verified_resources.csv": () => import("@/data/samoa_expansion_verified_resources.csv?raw"),
  "saudi_arabia_telegram_intake_verified_resources.csv": () => import("@/data/saudi_arabia_telegram_intake_verified_resources.csv?raw"),
  "senegal_expansion_verified_resources.csv": () => import("@/data/senegal_expansion_verified_resources.csv?raw"),
  "serbia_expansion_verified_resources.csv": () => import("@/data/serbia_expansion_verified_resources.csv?raw"),
  "sierra_leone_expansion_verified_resources.csv": () => import("@/data/sierra_leone_expansion_verified_resources.csv?raw"),
  "singapore_official_math_verified_resources.csv": () => import("@/data/singapore_official_math_verified_resources.csv?raw"),
  "slovakia_expansion_verified_resources.csv": () => import("@/data/slovakia_expansion_verified_resources.csv?raw"),
  "slovenia_expansion_verified_resources.csv": () => import("@/data/slovenia_expansion_verified_resources.csv?raw"),
  "solomon_islands_expansion_verified_resources.csv": () => import("@/data/solomon_islands_expansion_verified_resources.csv?raw"),
  "south_africa_computer_olympiad_verified_resources.csv": () => import("@/data/south_africa_computer_olympiad_verified_resources.csv?raw"),
  "south_africa_dbe_ana_2013_verified_resources.csv": () => import("@/data/south_africa_dbe_ana_2013_verified_resources.csv?raw"),
  "south_africa_dbe_math_verified_resources.csv": () => import("@/data/south_africa_dbe_math_verified_resources.csv?raw"),
  "south_africa_femssisa_expansion_verified_resources.csv": () => import("@/data/south_africa_femssisa_expansion_verified_resources.csv?raw"),
  "south_africa_foundation_math_verified_resources.csv": () => import("@/data/south_africa_foundation_math_verified_resources.csv?raw"),
  "south_africa_junior_math_verified_resources.csv": () => import("@/data/south_africa_junior_math_verified_resources.csv?raw"),
  "south_africa_samf_verified_resources.csv": () => import("@/data/south_africa_samf_verified_resources.csv?raw"),
  "south_africa_telegram_intake_verified_resources.csv": () => import("@/data/south_africa_telegram_intake_verified_resources.csv?raw"),
  "south_africa_uct_2018_verified_resources.csv": () => import("@/data/south_africa_uct_2018_verified_resources.csv?raw"),
  "south_africa_uj_math_followup_verified_resources.csv": () => import("@/data/south_africa_uj_math_followup_verified_resources.csv?raw"),
  "south_africa_uj_math_verified_resources.csv": () => import("@/data/south_africa_uj_math_verified_resources.csv?raw"),
  "south_africa_upmc_verified_resources.csv": () => import("@/data/south_africa_upmc_verified_resources.csv?raw"),
  "south_africa_wits_verified_resources.csv": () => import("@/data/south_africa_wits_verified_resources.csv?raw"),
  "south_southeast_asia_resources.csv": () => import("@/data/south_southeast_asia_resources.csv?raw"),
  "spain_expansion_verified_resources.csv": () => import("@/data/spain_expansion_verified_resources.csv?raw"),
  "sri_lanka_ousl_verified_resources.csv": () => import("@/data/sri_lanka_ousl_verified_resources.csv?raw"),
  "switzerland_expansion_verified_resources.csv": () => import("@/data/switzerland_expansion_verified_resources.csv?raw"),
  "syria_expansion_verified_resources.csv": () => import("@/data/syria_expansion_verified_resources.csv?raw"),
  "tajikistan_expansion_verified_resources.csv": () => import("@/data/tajikistan_expansion_verified_resources.csv?raw"),
  "tanzania_necta_verified_resources.csv": () => import("@/data/tanzania_necta_verified_resources.csv?raw"),
  "thailand_chula_2007_practice_verified_resources.csv": () => import("@/data/thailand_chula_2007_practice_verified_resources.csv?raw"),
  "thailand_chula_icpc2024_editorials_verified_resources.csv": () => import("@/data/thailand_chula_icpc2024_editorials_verified_resources.csv?raw"),
  "thailand_chula_verified_resources.csv": () => import("@/data/thailand_chula_verified_resources.csv?raw"),
  "thailand_icpc_2024_solutions_verified_resources.csv": () => import("@/data/thailand_icpc_2024_solutions_verified_resources.csv?raw"),
  "thailand_icpc_bangkok2025_verified_resources.csv": () => import("@/data/thailand_icpc_bangkok2025_verified_resources.csv?raw"),
  "thailand_kku_2009_homework_verified_resources.csv": () => import("@/data/thailand_kku_2009_homework_verified_resources.csv?raw"),
  "thailand_kku_2010_assessments_verified_resources.csv": () => import("@/data/thailand_kku_2010_assessments_verified_resources.csv?raw"),
  "thailand_kku_2010_quizzes_verified_resources.csv": () => import("@/data/thailand_kku_2010_quizzes_verified_resources.csv?raw"),
  "thailand_kku_2011_assessments_verified_resources.csv": () => import("@/data/thailand_kku_2011_assessments_verified_resources.csv?raw"),
  "thailand_kku_2012_homework_verified_resources.csv": () => import("@/data/thailand_kku_2012_homework_verified_resources.csv?raw"),
  "thailand_kku_2014_2013_exams_verified_resources.csv": () => import("@/data/thailand_kku_2014_2013_exams_verified_resources.csv?raw"),
  "thailand_kku_2014_verified_resources.csv": () => import("@/data/thailand_kku_2014_verified_resources.csv?raw"),
  "thailand_kku_discrete_followup_verified_resources.csv": () => import("@/data/thailand_kku_discrete_followup_verified_resources.csv?raw"),
  "thailand_kku_discrete_snapshot_verified_resources.csv": () => import("@/data/thailand_kku_discrete_snapshot_verified_resources.csv?raw"),
  "thailand_kku_dm_verified_resources.csv": () => import("@/data/thailand_kku_dm_verified_resources.csv?raw"),
  "thailand_kmitl_discrete_followup_verified_resources.csv": () => import("@/data/thailand_kmitl_discrete_followup_verified_resources.csv?raw"),
  "thailand_mahidol_muic_math_verified_resources.csv": () => import("@/data/thailand_mahidol_muic_math_verified_resources.csv?raw"),
  "thailand_muic_verified_resources.csv": () => import("@/data/thailand_muic_verified_resources.csv?raw"),
  "thailand_siit_verified_resources.csv": () => import("@/data/thailand_siit_verified_resources.csv?raw"),
  "thailand_timo_verified_resources.csv": () => import("@/data/thailand_timo_verified_resources.csv?raw"),
  "timor_leste_expansion_verified_resources.csv": () => import("@/data/timor_leste_expansion_verified_resources.csv?raw"),
  "togo_expansion_verified_resources.csv": () => import("@/data/togo_expansion_verified_resources.csv?raw"),
  "tonga_expansion_verified_resources.csv": () => import("@/data/tonga_expansion_verified_resources.csv?raw"),
  "trinidad_and_tobago_expansion_verified_resources.csv": () => import("@/data/trinidad_and_tobago_expansion_verified_resources.csv?raw"),
  "tunisia_expansion_verified_resources.csv": () => import("@/data/tunisia_expansion_verified_resources.csv?raw"),
  "turkiye_expansion_verified_resources.csv": () => import("@/data/turkiye_expansion_verified_resources.csv?raw"),
  "turkiye_tubitak_verified_resources.csv": () => import("@/data/turkiye_tubitak_verified_resources.csv?raw"),
  "uganda_uneb_verified_resources.csv": () => import("@/data/uganda_uneb_verified_resources.csv?raw"),
  "ukraine_expansion_verified_resources.csv": () => import("@/data/ukraine_expansion_verified_resources.csv?raw"),
  "united_arab_emirates_expansion_verified_resources.csv": () => import("@/data/united_arab_emirates_expansion_verified_resources.csv?raw"),
  "united_kingdom_bmo_verified_resources.csv": () => import("@/data/united_kingdom_bmo_verified_resources.csv?raw"),
  "united_kingdom_telegram_intake_verified_resources.csv": () => import("@/data/united_kingdom_telegram_intake_verified_resources.csv?raw"),
  "united_states_telegram_intake_verified_resources.csv": () => import("@/data/united_states_telegram_intake_verified_resources.csv?raw"),
  "united_states_usaco_2026_verified_resources.csv": () => import("@/data/united_states_usaco_2026_verified_resources.csv?raw"),
  "united_states_usaco_verified_resources.csv": () => import("@/data/united_states_usaco_verified_resources.csv?raw"),
  "uzbekistan_expansion_verified_resources.csv": () => import("@/data/uzbekistan_expansion_verified_resources.csv?raw"),
  "venezuela_expansion_verified_resources.csv": () => import("@/data/venezuela_expansion_verified_resources.csv?raw"),
  "vietnam_expansion_verified_resources.csv": () => import("@/data/vietnam_expansion_verified_resources.csv?raw"),
  "zambia_expansion_verified_resources.csv": () => import("@/data/zambia_expansion_verified_resources.csv?raw"),
  "zimbabwe_buse_verified_resources.csv": () => import("@/data/zimbabwe_buse_verified_resources.csv?raw"),
};

export const coreChunkNames = [
  "european_wave_resources.csv",
  "free_resources.csv",
  "important_country_resources.csv",
  "next_european_wave_resources.csv",
  "south_southeast_asia_resources.csv"
] as const;

export const catalogIndexTotals = {
  "catalogCount": 3586,
  "freeCount": 3586,
  "sourceCount": 412,
  "gatewayCount": 50,
  "trackCounts": {
    "GA": 1902,
    "EM": 1749,
    "DM": 1451,
    "CS": 336,
    "S": 0,
    "T": 0,
    "E": 0,
    "A": 0
  }
} as const;
