/* Signal Atlas data index: generated by scripts/build_catalog_index.py. Keep resource rows in lazy CSV chunks. */

export type CountryCatalogStat = { catalogCount: number; freeCount: number; caveatCount: number };

export const catalogCountryIndex: Record<string, CountryCatalogStat> = {
  "United States": {
    "catalogCount": 110,
    "freeCount": 110,
    "caveatCount": 3
  },
  "Canada": {
    "catalogCount": 123,
    "freeCount": 123,
    "caveatCount": 0
  },
  "France": {
    "catalogCount": 7,
    "freeCount": 7,
    "caveatCount": 3
  },
  "Australia": {
    "catalogCount": 100,
    "freeCount": 100,
    "caveatCount": 0
  },
  "New Zealand": {
    "catalogCount": 36,
    "freeCount": 36,
    "caveatCount": 0
  },
  "Japan": {
    "catalogCount": 6,
    "freeCount": 6,
    "caveatCount": 0
  },
  "Sweden": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "Finland": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  },
  "United Kingdom": {
    "catalogCount": 5,
    "freeCount": 5,
    "caveatCount": 0
  },
  "Global": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 1
  },
  "Germany": {
    "catalogCount": 5,
    "freeCount": 5,
    "caveatCount": 0
  },
  "Republic of Korea": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Singapore": {
    "catalogCount": 5,
    "freeCount": 5,
    "caveatCount": 1
  },
  "South Africa": {
    "catalogCount": 146,
    "freeCount": 146,
    "caveatCount": 1
  },
  "China": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 1
  },
  "India": {
    "catalogCount": 101,
    "freeCount": 101,
    "caveatCount": 0
  },
  "Indonesia": {
    "catalogCount": 44,
    "freeCount": 44,
    "caveatCount": 0
  },
  "Kenya": {
    "catalogCount": 7,
    "freeCount": 7,
    "caveatCount": 0
  },
  "Malaysia": {
    "catalogCount": 101,
    "freeCount": 101,
    "caveatCount": 0
  },
  "Nepal": {
    "catalogCount": 9,
    "freeCount": 9,
    "caveatCount": 0
  },
  "Netherlands": {
    "catalogCount": 81,
    "freeCount": 81,
    "caveatCount": 0
  },
  "Ireland": {
    "catalogCount": 4,
    "freeCount": 4,
    "caveatCount": 1
  },
  "Austria": {
    "catalogCount": 3,
    "freeCount": 3,
    "caveatCount": 0
  },
  "Nigeria": {
    "catalogCount": 403,
    "freeCount": 403,
    "caveatCount": 0
  },
  "Pakistan": {
    "catalogCount": 44,
    "freeCount": 44,
    "caveatCount": 0
  },
  "Philippines": {
    "catalogCount": 13,
    "freeCount": 13,
    "caveatCount": 0
  },
  "Rwanda": {
    "catalogCount": 18,
    "freeCount": 18,
    "caveatCount": 0
  },
  "Sri Lanka": {
    "catalogCount": 2,
    "freeCount": 2,
    "caveatCount": 0
  },
  "Tanzania": {
    "catalogCount": 4,
    "freeCount": 4,
    "caveatCount": 0
  },
  "Thailand": {
    "catalogCount": 87,
    "freeCount": 87,
    "caveatCount": 0
  },
  "Uganda": {
    "catalogCount": 4,
    "freeCount": 4,
    "caveatCount": 0
  },
  "Zimbabwe": {
    "catalogCount": 1,
    "freeCount": 1,
    "caveatCount": 0
  }
};

export const lazyChunksByCountry: Record<string, string[]> = {
  "Australia": [
    "archive_depth_resources.csv",
    "australia_amt_enrichment_verified_resources.csv",
    "australia_amt_verified_resources.csv",
    "australia_nesa_2014_mg_verified_resources.csv",
    "australia_nesa_2015_ext_verified_resources.csv",
    "australia_nesa_2015_verified_resources.csv",
    "australia_nesa_2016_2019_verified_resources.csv",
    "australia_nesa_2020_2023_verified_resources.csv",
    "australia_qcaa_2023_2025_verified_resources.csv",
    "australia_qcaa_2025_verified_resources.csv",
    "australia_scsa_2022_2025_verified_resources.csv",
    "australia_vcaa_2023_2025_verified_resources.csv",
    "australia_vcaa_guides_verified_resources.csv"
  ],
  "Canada": [
    "active_country_depth_resources.csv",
    "canada_cemc_bcc_2025_verified_resources.csv",
    "canada_cemc_verified_resources.csv",
    "four_country_depth_resources.csv"
  ],
  "France": [
    "active_country_depth_resources.csv"
  ],
  "India": [
    "india_gate_verified_resources.csv",
    "india_tifr_verified_resources.csv"
  ],
  "Indonesia": [
    "indonesia_binus_icpc2020_verified_resources.csv",
    "indonesia_binus_icpc2021_verified_resources.csv",
    "indonesia_binus_icpc2022_verified_resources.csv",
    "indonesia_ioi2022_verified_resources.csv"
  ],
  "Japan": [
    "archive_depth_resources.csv",
    "japan_mext_verified_resources.csv"
  ],
  "Kenya": [
    "kenya_must_verified_resources.csv",
    "kenya_university_math_verified_resources.csv"
  ],
  "Malaysia": [
    "malaysia_emos_imas2025_verified_resources.csv",
    "malaysia_emos_som2025_verified_resources.csv",
    "malaysia_imonst_verified_resources.csv",
    "malaysia_mcc2025_verified_resources.csv",
    "malaysia_mco2015_solutions_verified_resources.csv",
    "malaysia_mco_2023_verified_resources.csv",
    "malaysia_mco_2024_2025_verified_resources.csv",
    "malaysia_mco_codeforces_verified_resources.csv",
    "malaysia_mco_direct_tasks_verified_resources.csv",
    "malaysia_mco_verified_resources.csv",
    "malaysia_peninsula_dcs1123_verified_resources.csv",
    "malaysia_uitm_mo_verified_resources.csv"
  ],
  "Nepal": [
    "nepal_lec_verified_resources.csv",
    "nepal_mano_verified_resources.csv"
  ],
  "Netherlands": [
    "netherlands_math_olympiad_verified_resources.csv"
  ],
  "New Zealand": [
    "archive_depth_resources.csv"
  ],
  "Nigeria": [
    "nigeria_waec_verified_resources.csv"
  ],
  "Pakistan": [
    "pakistan_gcu_verified_resources.csv",
    "pakistan_giki_verified_resources.csv",
    "pakistan_iba_verified_resources.csv",
    "pakistan_pu_verified_resources.csv",
    "pakistan_university_followup_verified_resources.csv"
  ],
  "Philippines": [
    "philippines_noiph2020_eliminations_verified_resources.csv",
    "philippines_noiph2020_gym_verified_resources.csv",
    "philippines_noiph_pdf_verified_resources.csv"
  ],
  "Rwanda": [
    "rwanda_nesa_verified_resources.csv"
  ],
  "Singapore": [
    "singapore_official_math_verified_resources.csv"
  ],
  "South Africa": [
    "south_africa_foundation_math_verified_resources.csv",
    "south_africa_junior_math_verified_resources.csv",
    "south_africa_samf_verified_resources.csv",
    "south_africa_uct_2018_verified_resources.csv",
    "south_africa_uj_math_followup_verified_resources.csv",
    "south_africa_uj_math_verified_resources.csv",
    "south_africa_upmc_verified_resources.csv",
    "south_africa_wits_verified_resources.csv"
  ],
  "Sri Lanka": [
    "sri_lanka_ousl_verified_resources.csv"
  ],
  "Tanzania": [
    "tanzania_necta_verified_resources.csv"
  ],
  "Thailand": [
    "thailand_chula_2007_practice_verified_resources.csv",
    "thailand_chula_icpc2024_editorials_verified_resources.csv",
    "thailand_chula_verified_resources.csv",
    "thailand_icpc_bangkok2025_verified_resources.csv",
    "thailand_kku_2009_homework_verified_resources.csv",
    "thailand_kku_2010_assessments_verified_resources.csv",
    "thailand_kku_2010_quizzes_verified_resources.csv",
    "thailand_kku_2011_assessments_verified_resources.csv",
    "thailand_kku_2012_homework_verified_resources.csv",
    "thailand_kku_2014_2013_exams_verified_resources.csv",
    "thailand_kku_2014_verified_resources.csv",
    "thailand_kku_discrete_snapshot_verified_resources.csv",
    "thailand_kku_dm_verified_resources.csv",
    "thailand_mahidol_muic_math_verified_resources.csv",
    "thailand_muic_verified_resources.csv",
    "thailand_siit_verified_resources.csv"
  ],
  "Uganda": [
    "uganda_uneb_verified_resources.csv"
  ],
  "United States": [
    "active_country_depth_resources.csv",
    "united_states_usaco_2026_verified_resources.csv",
    "united_states_usaco_verified_resources.csv"
  ],
  "Zimbabwe": [
    "zimbabwe_buse_verified_resources.csv"
  ]
};

export const catalogIndexTotals = {
  "catalogCount": 1477,
  "freeCount": 1477,
  "sourceCount": 148,
  "gatewayCount": 0,
  "trackCounts": {
    "GA": 658,
    "EM": 596,
    "DM": 664
  }
} as const;
